import Link from 'next/link';
import {redirect,notFound} from 'next/navigation';
import {assignmentActor} from '@/lib/assignment-api';
import {prisma} from '@/lib/prisma';
import SubmissionCard from '@/components/assignments/submission-card';
export default async function GradesPage({params}:{params:Promise<{courseId:string}>}) {
 const actor=await assignmentActor();if(!actor)redirect('/login');const {courseId}=await params;
 const enrollment=await prisma.enrollment.findUnique({where:{userId_courseId:{userId:actor.id,courseId}},include:{course:{select:{title:true,slug:true,status:true}}}});
 if(!enrollment)notFound();
 const assignments=await prisma.assignment.findMany({where:{lesson:{section:{courseId}},OR:[{published:true,lesson:{status:'PUBLISHED'}},{submissions:{some:{enrollmentId:enrollment.id}}}]},orderBy:{createdAt:'asc'},include:{lesson:{select:{id:true,title:true}},submissions:{where:{enrollmentId:enrollment.id},orderBy:{attempt:'desc'}}}});
 const latest=assignments.map(a=>a.submissions[0]).filter(Boolean);const graded=latest.filter(s=>s.status==='GRADED');const average=graded.length?graded.reduce((sum,s)=>sum+(s.score??0),0)/graded.length:null;
 return <main className="mx-auto max-w-5xl px-4 py-8"><Link href="/dashboard" className="text-indigo-600">بازگشت به دوره‌های من</Link><h1 className="my-5 text-2xl font-bold">کارنامهٔ تکلیف‌ها · {enrollment.course.title}</h1><div className="rounded-2xl border bg-white p-5 text-sm leading-8"><p>تکلیف‌ها: {assignments.length.toLocaleString('fa-IR')} · نمرهٔ نهایی: {graded.length.toLocaleString('fa-IR')} · منتظر بررسی: {latest.filter(s=>s.status==='PENDING').length.toLocaleString('fa-IR')} · نیاز به اصلاح: {latest.filter(s=>s.status==='REVISION').length.toLocaleString('fa-IR')}</p><p>میانگین نمره‌های نهایی: {average===null?'هنوز نمره‌ای ثبت نشده':`${average.toLocaleString('fa-IR',{maximumFractionDigits:1})} از ۱۰۰`}</p><p className="text-xs text-slate-500">میانگین فقط از آخرین ارسالِ نمره‌دار هر تکلیف محاسبه می‌شود؛ تکلیف ارسال‌نشده یا منتظر بررسی صفر محسوب نمی‌شود. این کارنامه مربوط به تکلیف‌هاست و درصد پیشرفت ویدئوها را تغییر نمی‌دهد.</p></div>{enrollment.status==='CANCELLED'&&<p className="my-4 text-sm text-amber-800">ثبت‌نام لغو شده است؛ سوابق ارزیابی شما باقی می‌ماند ولی ارسال پاسخ جدید فعال نیست.</p>}<div className="my-6 space-y-5">{assignments.map(a=><section key={a.id} className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{a.submissions[0]?.assignmentTitle??a.title} · {a.lesson.title}</h2>{enrollment.status!=='CANCELLED'&&enrollment.course.status==='PUBLISHED'&&<Link href={`/courses/${enrollment.course.slug}/lessons/${a.lesson.id}`} className="my-3 inline-block text-sm text-indigo-600">رفتن به درس و تکلیف</Link>}{a.submissions.length?<div className="space-y-3">{a.submissions.map(s=><SubmissionCard key={s.id} submission={s}/>)}</div>:<p className="mt-3 text-sm text-slate-500">هنوز پاسخی ارسال نکرده‌اید. برای تکلیف درس قفل‌شده، ابتدا درس قبلی را تکمیل کنید.</p>}</section>)}</div>{!assignments.length&&<p className="my-5 rounded-xl border bg-white p-5">هنوز تکلیفی برای این دوره منتشر نشده است.</p>}</main>;
}
