import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {communicationActor,pageNumber,roleLabels,ticketScope,userLabel} from '@/lib/communication';
import {prisma} from '@/lib/prisma';
import {TicketReply} from '@/components/communication/forms';
export default async function TicketPage({params,searchParams}:{params:Promise<{ticketId:string}>;searchParams:Promise<{page?:string}>}){
 const actor=await communicationActor();if(!actor)redirect('/login');const {ticketId}=await params;
 const ticket=await prisma.ticket.findFirst({where:{id:ticketId,...ticketScope(actor)},include:{creator:{select:{id:true,name:true,role:true}},recipient:{select:{id:true,name:true,role:true}}}});if(!ticket)notFound();
 const count=await prisma.ticketMessage.count({where:{ticketId}});const pages=Math.max(1,Math.ceil(count/30));const query=await searchParams;const page=query.page?Math.min(pageNumber(query.page),pages):pages;
 const messages=await prisma.ticketMessage.findMany({where:{ticketId},orderBy:[{createdAt:'asc'},{id:'asc'}],skip:(page-1)*30,take:30,include:{sender:{select:{id:true,name:true,role:true}},attachments:{select:{id:true,filename:true,size:true}}}});
 return <main className="mx-auto max-w-4xl px-4 py-8"><Link href="/tickets" className="panel-action panel-action-slate">بازگشت به تیکت‌ها</Link><header className="my-6 rounded-2xl border bg-white p-6"><h1 className="break-words text-2xl font-bold">{ticket.subject}</h1><p className="mt-3 text-sm text-slate-500">{userLabel(ticket.creator)} · {ticket.recipient?userLabel(ticket.recipient):'پشتیبانی مدیریت'} · {ticket.status==='OPEN'?'باز':'بسته'}</p><p className="mt-2 text-xs text-slate-500">این گفت‌وگو برای دو طرف و مدیران قابل مشاهده است.</p></header><div className="space-y-4">{messages.map(message=><article key={message.id} className={`rounded-2xl border p-5 ${message.senderId===actor.userId?'border-indigo-100 bg-indigo-50/60 sm:ms-12':'border-slate-200 bg-white sm:me-12'}`}><header className="flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500"><span>{userLabel(message.sender)} · {roleLabels[message.sender.role]}</span><time dateTime={message.createdAt.toISOString()}>{message.createdAt.toLocaleString('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'})}</time></header><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-8">{message.body}</p>{message.attachments.map(file=><a key={file.id} href={`/api/tickets/attachments/${file.id}`} className="panel-action mt-4 max-w-full break-all" download>دانلود {file.filename} <span className="shrink-0 text-xs">({Math.ceil(file.size/1024).toLocaleString('fa-IR')} کیلوبایت)</span></a>)}</article>)}</div><nav className="my-5 flex items-center justify-center gap-3">{page>1&&<Link scroll={false} href={`?page=${page-1}`} className="panel-action panel-action-slate">پیام‌های قبلی</Link>}<span className="text-sm">{page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span>{page<pages&&<Link scroll={false} href={`?page=${page+1}`} className="panel-action panel-action-slate">پیام‌های بعدی</Link>}</nav><section className="rounded-2xl border bg-white p-6"><TicketReply ticketId={ticket.id} status={ticket.status}/></section></main>;
}
