'use client';
import {useState,type FormEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import ThemeIcon from '@/components/panel/theme-icon';
import NumberInput from '@/components/ui/number-input';
import {Spinner} from '@/components/panel/loading';
function Form({url,method='PUT',payload,children,label='ذخیره',disabled=false}:{url:string;method?:string;payload:(f:FormData)=>unknown;children:ReactNode;label?:string;disabled?:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const data=payload(new FormData(e.currentTarget));setBusy(true);setMessage('');try{const res=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.message||'ذخیره انجام نشد.');setMessage('ذخیره شد.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'ارتباط برقرار نشد.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="assessment-form space-y-4"><fieldset disabled={busy||disabled} className="space-y-4">{children}<button className="panel-action panel-action-primary" type="submit">{busy?<Spinner small/>:<ThemeIcon name="check" className="h-5 w-5"/>}{label}</button></fieldset><p role="status" className="min-h-6 text-sm text-indigo-800">{message}</p></form>;
}
export function ExamEditor({courseId,exam,locked}:{courseId:string;exam:{title:string;instructions:string;questions:string[];published:boolean;version:number;examWeight:number}|null;locked:boolean}){
 return <Form url={`/api/courses/${courseId}/exam`} disabled={locked} payload={f=>({title:f.get('title'),instructions:f.get('instructions'),questions:String(f.get('questions')).split('\n').map(s=>s.trim()).filter(Boolean),published:f.get('published')==='on',version:exam?.version??0,examWeight:Number(f.get('weight'))})} label="ذخیرهٔ آزمون"><label>عنوان آزمون<input name="title" required minLength={3} maxLength={150} defaultValue={exam?.title??'آزمون پایانی دوره'}/></label><label>راهنمای آزمون<textarea name="instructions" maxLength={5000} defaultValue={exam?.instructions}/></label><label>سؤال‌های تشریحی؛ هر سؤال در یک خط<textarea name="questions" required rows={6} maxLength={30000} defaultValue={exam?.questions.join('\n')}/><span className="form-help">از یک تا سی سؤال؛ هر سؤال حداکثر هزار نویسه. دانش‌آموز یک بار پاسخ نهایی می‌فرستد.</span></label><label>سهم آزمون در نمرهٔ کل (درصد)<NumberInput name="weight" min={0} max={100} unit="درصد" required defaultValue={exam?.examWeight??50}/><span className="form-help">باقی سهم برای میانگین تمرین‌هاست. اگر تمرینی منتشر نشده باشد، نمرهٔ کل همان آزمون است.</span></label><label className="flex items-center gap-2"><input type="checkbox" name="published" defaultChecked={exam?.published}/>انتشار آزمون</label><p className="text-sm text-amber-800">{locked?'پاسخ دریافت شده است؛ صورت آزمون و سهم نمره برای حفظ سوابق قابل تغییر نیست.':'پس از اولین پاسخ، سؤال‌ها و سهم نمره ثابت می‌شوند.'}</p></Form>;
}
export function ExamAnswer({courseId,version,questions}:{courseId:string;version:number;questions:string[]}){return <Form url={`/api/courses/${courseId}/exam/submit`} method="POST" label="ثبت پاسخ نهایی" payload={f=>({version,answers:questions.map((_,i)=>f.get(`q${i}`))})}>{questions.map((q,i)=><label key={i}>{(i+1).toLocaleString('fa-IR')}. {q}<textarea required maxLength={5000} rows={4} name={`q${i}`}/></label>)}<p className="text-sm text-amber-800">قبل از ثبت، پاسخ‌ها را مرور کنید؛ پس از ارسال امکان ویرایش ندارید.</p></Form>}
export function ExamGrade({enrollmentId}:{enrollmentId:string}){return <Form url={`/api/enrollments/${enrollmentId}/exam-grade`} method="POST" label="ثبت نمرهٔ آزمون" payload={f=>({score:Number(f.get('score')),feedback:f.get('feedback')})}><label>نمره از صد<NumberInput name="score" min={0} max={100} unit="از صد" required/><span className="form-help">نمره پس از ثبت در کارنامه نمایش داده می‌شود و قابل ویرایش نیست.</span></label><label>بازخورد پاسخ آزمون<textarea name="feedback" required minLength={3} maxLength={4000}/></label></Form>}
export function FinalNote({enrollmentId,note,role}:{enrollmentId:string;note:string;role:string}){return <Form url={`/api/enrollments/${enrollmentId}/final-note`} payload={f=>({note:f.get('note')})} label="ذخیرهٔ بازخورد"><label>{role==='ADMIN'?'بازخورد مدیر برای دانش‌آموز و والدین':'بازخورد کلی مدرس برای والدین و دانش‌آموز'}<textarea name="note" rows={4} maxLength={4000} defaultValue={note}/></label><p className="text-xs text-slate-500">این متن در کارنامهٔ همین دانش‌آموز نمایش داده می‌شود.</p></Form>}
export function ReviewForm({courseId,review}:{courseId:string;review:{rating:number;body:string;authorType:string}|null}){return <Form url={`/api/courses/${courseId}/review`} label="ثبت نظر دوره" payload={f=>({authorType:f.get('authorType'),rating:Number(f.get('rating')),body:f.get('body')})}><label>نظر از طرف<select name="authorType" defaultValue={review?.authorType??'STUDENT'}><option value="STUDENT">دانش‌آموز</option><option value="PARENT">والدین، از حساب دانش‌آموز</option></select></label><label>امتیاز دوره<select name="rating" defaultValue={review?.rating??5}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n.toLocaleString('fa-IR')} از ۵</option>)}</select></label><label>نظر و پیشنهاد شما<textarea name="body" required minLength={5} maxLength={4000} rows={4} defaultValue={review?.body}/></label><p className="text-xs text-slate-500">نظر برای مدرس دوره و مدیر قابل مشاهده است و عمومی منتشر نمی‌شود. می‌توانید نظر خود را به‌روز کنید.</p></Form>}
