'use client';
import {useState,type FormEvent,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import ThemeIcon from '@/components/panel/theme-icon';
import NumberInput from '@/components/ui/number-input';
import {normalizeQuestions,type ExamQuestion,type PublicQuestion} from '@/lib/exam-questions';
import {Spinner} from '@/components/panel/loading';
function Form({url,method='PUT',payload,children,label='ذخیره',disabled=false}:{url:string;method?:string;payload:(f:FormData)=>unknown;children:ReactNode;label?:string;disabled?:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const data=payload(new FormData(e.currentTarget));setBusy(true);setMessage('');try{const res=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await res.json();if(!res.ok)throw Error(result.message||'ذخیره انجام نشد.');setMessage('ذخیره شد.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'ارتباط برقرار نشد.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="assessment-form space-y-4"><fieldset disabled={busy||disabled} className="space-y-4">{children}<button className="panel-action panel-action-primary" type="submit">{busy?<Spinner small/>:<ThemeIcon name="check" className="h-5 w-5"/>}{label}</button></fieldset><p role="status" className="min-h-6 text-sm text-indigo-800">{message}</p></form>;
}
export function ExamEditor({courseId,exam,locked}:{courseId:string;exam:{title:string;instructions:string;questions:unknown;published:boolean;version:number;examWeight:number}|null;locked:boolean}){
 const [questions,setQuestions]=useState<ExamQuestion[]>(()=>exam?normalizeQuestions(exam.questions):[{type:'CHOICE',prompt:'',options:['','','',''],correctOption:0}]);
 function change(index:number,q:ExamQuestion){setQuestions(items=>items.map((item,i)=>i===index?q:item));}
 return <Form url={`/api/courses/${courseId}/exam`} disabled={locked} payload={f=>({title:f.get('title'),instructions:f.get('instructions'),questions,published:f.get('published')==='on',version:exam?.version??0,examWeight:Number(f.get('weight'))})} label="ذخیرهٔ آزمون"><label>عنوان آزمون<input name="title" required minLength={3} maxLength={150} defaultValue={exam?.title??'آزمون پایانی دوره'}/></label><label>راهنمای آزمون<textarea name="instructions" maxLength={5000} defaultValue={exam?.instructions}/></label><div className="space-y-4">{questions.map((q,i)=><section className="question-editor" key={i}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">سؤال {(i+1).toLocaleString('fa-IR')}</h3><button type="button" disabled={questions.length===1} className="panel-action panel-action-slate" onClick={()=>setQuestions(questions.filter((_,n)=>n!==i))}><ThemeIcon name="trash" className="h-4 w-4"/>حذف سؤال</button></div><label>نوع سؤال<select value={q.type} onChange={e=>change(i,e.target.value==='TEXT'?{type:'TEXT',prompt:q.prompt}:{type:'CHOICE',prompt:q.prompt,options:['','','',''],correctOption:0})}><option value="CHOICE">چهارگزینه‌ای</option><option value="TEXT">تشریحی</option></select></label><label>متن سؤال<textarea required minLength={3} maxLength={1000} value={q.prompt} onChange={e=>change(i,{...q,prompt:e.target.value})}/></label>{q.type==='CHOICE'&&<><div className="grid gap-3 sm:grid-cols-2">{q.options.map((option,n)=><label key={n}>گزینهٔ {(n+1).toLocaleString('fa-IR')}<input required maxLength={500} value={option} onChange={e=>change(i,{...q,options:q.options.map((o,j)=>j===n?e.target.value:o)})}/></label>)}</div><label>گزینهٔ صحیح<select value={q.correctOption} onChange={e=>change(i,{...q,correctOption:Number(e.target.value)})}>{[0,1,2,3].map(n=><option key={n} value={n}>گزینهٔ {(n+1).toLocaleString('fa-IR')}</option>)}</select></label></>}</section>)}</div><button type="button" disabled={questions.length>=30} className="panel-action" onClick={()=>setQuestions([...questions,{type:'CHOICE',prompt:'',options:['','','',''],correctOption:0}])}><ThemeIcon name="plus" className="h-4 w-4"/>افزودن سؤال</button><p className="text-xs leading-7 text-slate-500">حداکثر سی سؤال با سهم برابر. چهارگزینه‌ای‌ها خودکار و بدون نمرهٔ منفی تصحیح می‌شوند؛ بخش تشریحی را مدرس ارزیابی می‌کند.</p><label>سهم آزمون در نمرهٔ کل (درصد)<NumberInput name="weight" min={0} max={100} unit="درصد" required defaultValue={exam?.examWeight??50}/></label><label><input type="checkbox" name="published" defaultChecked={exam?.published}/>انتشار آزمون</label><p className="text-sm text-amber-800">{locked?'پاسخ دریافت شده؛ سؤال‌ها و سهم نمره ثابت هستند.':'پس از اولین پاسخ، سؤال‌ها و سهم نمره ثابت می‌شوند.'}</p></Form>;
}
export function ExamAnswer({courseId,version,questions}:{courseId:string;version:number;questions:PublicQuestion[]}){return <Form url={`/api/courses/${courseId}/exam/submit`} method="POST" label="ثبت پاسخ نهایی" payload={f=>({version,answers:questions.map((_,i)=>f.get(`q${i}`))})}>{questions.map((q,i)=><fieldset key={i} className="question-editor"><legend className="px-2 font-bold">{(i+1).toLocaleString('fa-IR')}. {q.prompt}</legend>{q.type==='TEXT'?<label>پاسخ تشریحی<textarea required maxLength={5000} rows={4} name={`q${i}`}/></label>:<div className="space-y-3">{q.options.map((option,n)=><label key={n} className="choice-option"><input type="radio" required name={`q${i}`} value={n}/><span>{option}</span></label>)}</div>}</fieldset>)}<p className="text-sm text-amber-800">هر سؤال سهم برابر دارد و نمرهٔ منفی نداریم. قبل از ثبت پاسخ‌ها را مرور کنید؛ پس از ارسال امکان ویرایش ندارید.</p></Form>}
export function ExamGrade({enrollmentId}:{enrollmentId:string}){return <Form url={`/api/enrollments/${enrollmentId}/exam-grade`} method="POST" label="ثبت نمرهٔ آزمون" payload={f=>({score:Number(f.get('score')),feedback:f.get('feedback')})}><label>میانگین نمرهٔ سؤال‌های تشریحی از صد<NumberInput name="score" min={0} max={100} unit="از صد" required/><span className="form-help">نمرهٔ چهارگزینه‌ای‌ها خودکار محاسبه می‌شود؛ فقط بخش تشریحی را ارزیابی کنید. نمره پس از ثبت قابل ویرایش نیست.</span></label><label>بازخورد پاسخ آزمون<textarea name="feedback" required minLength={3} maxLength={4000}/></label></Form>}
export function FinalNote({enrollmentId,note,role}:{enrollmentId:string;note:string;role:string}){return <Form url={`/api/enrollments/${enrollmentId}/final-note`} payload={f=>({note:f.get('note')})} label="ذخیرهٔ بازخورد"><label>{role==='ADMIN'?'بازخورد مدیر برای دانش‌آموز و والدین':'بازخورد کلی مدرس برای والدین و دانش‌آموز'}<textarea name="note" rows={4} maxLength={4000} defaultValue={note}/></label><p className="text-xs text-slate-500">این متن در کارنامهٔ همین دانش‌آموز نمایش داده می‌شود.</p></Form>}
export function ReviewForm({courseId,review}:{courseId:string;review:{rating:number;body:string;authorType:string}|null}){return <Form url={`/api/courses/${courseId}/review`} label="ثبت نظر دوره" payload={f=>({authorType:f.get('authorType'),rating:Number(f.get('rating')),body:f.get('body')})}><label>نظر از طرف<select name="authorType" defaultValue={review?.authorType??'STUDENT'}><option value="STUDENT">دانش‌آموز</option><option value="PARENT">والدین، از حساب دانش‌آموز</option></select></label><label>امتیاز دوره<select name="rating" defaultValue={review?.rating??5}>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n.toLocaleString('fa-IR')} از ۵</option>)}</select></label><label>نظر و پیشنهاد شما<textarea name="body" required minLength={5} maxLength={4000} rows={4} defaultValue={review?.body}/></label><p className="text-xs text-slate-500">نظر برای مدرس دوره و مدیر قابل مشاهده است و عمومی منتشر نمی‌شود. می‌توانید نظر خود را به‌روز کنید.</p></Form>}
