"use client";
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import CertificateDocument from '@/components/assessment/certificate-document';
import {defaultDesign,styleLabels,type CertificateDesign} from '@/lib/certificate-templates';
import ThemeIcon from '@/components/panel/theme-icon';
export function TemplateEditor({initial,previewDate}:{initial?:CertificateDesign&{id:string};previewDate:string}){
 const [design,setDesign]=useState<CertificateDesign>(initial||defaultDesign),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 return <div className="grid items-start gap-7 xl:grid-cols-[340px_1fr]"><form className="assessment-card assessment-form space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const res=await fetch('/api/admin/certificate-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...design,id:initial?.id})});const data=await res.json();if(!res.ok)throw Error(data.message);setMessage(data.message);router.replace(`/admin/certificates/templates?edit=${data.id}`,{scroll:false});router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}}>
 <fieldset disabled={busy} className="space-y-4"><label>نام قالب<input required maxLength={80} value={design.name} onChange={e=>setDesign({...design,name:e.target.value})}/></label><label>سبک طراحی<select value={design.style} onChange={e=>setDesign({...design,style:e.target.value as CertificateDesign['style']})}>{Object.entries(styleLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>رنگ اصلی<input type="color" value={design.accent} onChange={e=>setDesign({...design,accent:e.target.value})}/></label><label>نام مجموعه<input required maxLength={100} value={design.issuer} onChange={e=>setDesign({...design,issuer:e.target.value})}/></label><label>نام انگلیسی مجموعه<input required dir="ltr" maxLength={100} value={design.issuerEn} onChange={e=>setDesign({...design,issuerEn:e.target.value})}/></label><label>نام تأییدکننده<input maxLength={100} value={design.signatory} onChange={e=>setDesign({...design,signatory:e.target.value})}/></label><label className="flex gap-2"><input type="checkbox" checked={design.active} onChange={e=>setDesign({...design,active:e.target.checked})}/>قالب فعال</label><button className="panel-action panel-action-primary"><ThemeIcon name="check"/><span>{busy?'در حال ذخیره…':'ذخیرهٔ قالب'}</span></button></fieldset><p role="status" className="text-sm leading-7">{message}</p></form>
 <div><p className="mb-4 text-sm text-slate-500">پیش‌نمایش زنده؛ این نمونه مدرک صادرشده نیست.</p><CertificateDocument design={design} studentName="نام دانش‌آموز" courseTitle="عنوان دورهٔ آموزشی" score={90} issuedAt={new Date(previewDate)} id="SAMPLE — نمونهٔ طراحی" preview/></div></div>;
}
export function AssignCertificateTemplate({courses,templates}:{courses:{id:string;title:string;certificateTemplateId:string|null}[];templates:{id:string;name:string}[]}){
 const [courseId,setCourseId]=useState(courses[0]?.id||''),[templateId,setTemplateId]=useState(courses[0]?.certificateTemplateId||''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();
 return <form className="assessment-form space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const res=await fetch('/api/admin/certificate-templates',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseId,templateId:templateId||null})});const data=await res.json();if(!res.ok)throw Error(data.message);setMessage(data.message);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}}><div className="grid gap-4 md:grid-cols-2"><label>دوره<select required value={courseId} onChange={e=>{setCourseId(e.target.value);setTemplateId(courses.find(c=>c.id===e.target.value)?.certificateTemplateId||'');}}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>قالب صدور<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">کلاسیک پیش‌فرض</option>{templateId&&!templates.some(t=>t.id===templateId)&&<option value={templateId}>قالب فعلی غیرفعال است؛ انتخاب را تغییر دهید</option>}{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label></div><button className="panel-action" disabled={busy||!courseId}><ThemeIcon name="award"/><span>ذخیرهٔ قالب دوره</span></button><p role="status" className="text-sm">{message}</p></form>;
}
