"use client";
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import NumberInput from '@/components/ui/number-input';
import ThemeIcon from '@/components/panel/theme-icon';
type Course={id:string;title:string};
async function post(url:string,body:unknown){const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw Error(data.message||'درخواست انجام نشد.');return data;}
export function CouponForm({courses}:{courses:Course[]}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 return <form className="assessment-form space-y-4" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{const data=await post('/api/admin/coupons',{code:f.get('code'),percent:Number(f.get('percent')),courseId:f.get('courseId')||null,active:f.get('active')==='on'});setMessage(data.message);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-4"><label>کد تخفیف<input name="code" required dir="ltr" minLength={3} maxLength={40} pattern="[A-Za-z0-9_\-]+"/></label><label>درصد تخفیف<NumberInput name="percent" min={1} max={100} required defaultValue={10} unit="درصد"/></label><label>محدودهٔ اعتبار<select name="courseId"><option value="">همهٔ دوره‌ها</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label className="flex items-center gap-2"><input name="active" type="checkbox" defaultChecked/>فعال</label><p className="text-xs leading-7">برای ویرایش یا غیرفعال‌سازی، همان کد را وارد کنید. درصد روی قیمت فعلی پس از تخفیف دوره اعمال می‌شود؛ پرداخت‌های قبلی تغییر نمی‌کنند.</p><button className="panel-action panel-action-primary"><ThemeIcon name="check" className="h-4 w-4"/>ذخیرهٔ کد</button></fieldset><p role="status">{message}</p></form>;
}
export function SmsRunner({campaignId,retryId}:{campaignId:string;retryId?:string}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const stop=useRef(false);const router=useRouter();useEffect(()=>()=>{stop.current=true;},[]);
 return <div className="my-3"><div className="flex flex-wrap gap-2"><button disabled={busy} className="panel-action" onClick={async()=>{if(retryId&&!confirm('نتیجهٔ قبلی را در پنل پیامک بررسی کرده‌اید؟ ارسال مجدد ممکن است تکراری باشد.'))return;stop.current=false;setBusy(true);try{let first=true;while(!stop.current){const result=await post('/api/admin/sms',{campaignId,...(first&&retryId?{retryId,confirmRetry:true}:{})});first=false;if(!result.configured){setMessage('ابتدا تنظیمات سرویس پیامکی را وارد کنید.');break;}if(!result.processed){setMessage('صف پردازش شد؛ نتیجهٔ هر شماره را بررسی کنید.');break;}setMessage('در حال پردازش؛ صفحه را باز نگه دارید.');}}catch(e){setMessage(e instanceof Error?e.message:'خطا');}finally{setBusy(false);router.refresh();}}}><ThemeIcon name="message" className="h-4 w-4"/>{busy?'در حال ارسال…':retryId?'تلاش مجدد پس از بررسی':'ارسال / ادامهٔ ارسال'}</button>{busy&&<button className="panel-action" onClick={()=>{stop.current=true;setMessage('پس از پایان این دسته متوقف می‌شود.');}}>توقف</button>}</div><p className="mt-2 text-xs" role="status">{message}</p></div>;
}
export function SmsForm(){
 const router=useRouter();const [pattern,setPattern]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const requestId=useRef<string|null>(null);
 return <form className="assessment-form space-y-4" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setBusy(true);try{requestId.current??=crypto.randomUUID();await post('/api/admin/sms',{requestId:requestId.current,audience:f.get('audience'),message:pattern?'':f.get('message'),patternCode:pattern?f.get('patternCode'):undefined,variables:pattern?JSON.parse(String(f.get('variables')||'{}')):{}});requestId.current=null;setMessage('فهرست گیرندگان آماده شد؛ در تاریخچه دکمهٔ ارسال را بزنید.');form.reset();router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'خطا');}finally{setBusy(false);}}}><fieldset disabled={busy} className="space-y-4"><label>گیرندگان<select name="audience"><option value="ALL">همهٔ کاربران</option><option value="TEACHER">مدرس‌ها</option><option value="STUDENT">دانش‌آموزان</option></select></label><label>روش پیام<select value={pattern?'pattern':'simple'} onChange={e=>setPattern(e.target.value==='pattern')}><option value="simple">پیامک ساده</option><option value="pattern">پترن تأییدشدهٔ سرویس</option></select></label>{pattern?<><label>کد پترن<input required name="patternCode" maxLength={100} dir="ltr"/></label><label>متغیرهای پترن (JSON)<textarea name="variables" dir="ltr" defaultValue={'{"message":"شروع کلاس"}'} required/></label></>:<label>متن پیامک<textarea name="message" required maxLength={1500} rows={4}/></label>}<p className="text-xs leading-7">شماره‌های معتبر و غیرآزمایشی انتخاب می‌شوند. هر شماره در این ارسال فقط یک بار قرار می‌گیرد. هزینه و پذیرش پترن تابع پنل پیامکی شماست.</p><button className="panel-action panel-action-primary"><ThemeIcon name="users" className="h-4 w-4"/>آماده‌سازی فهرست گیرندگان</button></fieldset><p role="status">{message}</p></form>;
}
