'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {Spinner} from '@/components/panel/loading';

export function NotificationRead({id,href}:{id?:string;href?:string}){
 const router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function mark(){setBusy(true);setError('');try{const res=await fetch('/api/notifications/read',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{id}:{all:true})});if(!res.ok)throw Error('ثبت وضعیت انجام نشد.');window.dispatchEvent(new Event('notifications-changed'));if(href)router.push(href);router.refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <span className="inline-flex flex-col gap-2"><button disabled={busy} onClick={()=>void mark()} className="panel-action panel-action-slate">{busy?<Spinner small/>:id?(href?'مشاهده و خواندن':'خواندم'):'خواندن همهٔ اعلان‌ها'}</button>{error&&<span role="alert" className="text-xs text-rose-700">{error}</span>}</span>;
}
export function NotificationBell(){
 const [unread,setUnread]=useState<number|null>(null);const [open,setOpen]=useState(false);const [items,setItems]=useState<{id:string;title:string;readAt:string|null}[]>([]);const [failed,setFailed]=useState(false);const path=usePathname();const root=useRef<HTMLDivElement>(null);const trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{
  const controller=new AbortController();let active=true;let running=false;
  async function refresh(){if(running||document.visibilityState==='hidden')return;running=true;try{const res=await fetch('/api/notifications',{cache:'no-store',signal:controller.signal});if(!res.ok)throw Error();const data=await res.json();if(active){setUnread(data.unread);setItems(data.items);setFailed(false);}}catch{if(active)setFailed(true);}finally{running=false;}}
  void refresh();const timer=setInterval(()=>void refresh(),30000);
  window.addEventListener('notifications-changed',refresh);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);
  return()=>{active=false;controller.abort();clearInterval(timer);window.removeEventListener('notifications-changed',refresh);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};
 },[path]);
 useEffect(()=>{if(!open)return;function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false);}function escape(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);trigger.current?.focus();}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[open]);
 return <div className="relative" ref={root}><button ref={trigger} type="button" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="notification-popover" aria-label={`اعلان‌ها${unread===null?'':`، ${unread.toLocaleString('fa-IR')} خوانده‌نشده`}`} className="relative flex h-11 w-11 items-center justify-center rounded-2xl border border-slate-200 bg-slate-50 text-slate-600 transition hover:bg-indigo-50 focus-visible:outline-2 focus-visible:outline-indigo-500"><svg aria-hidden="true" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4M12 2V1"/></svg>{!!unread&&<span className="absolute -right-2 -top-2 min-w-5 rounded-full bg-rose-600 px-1 text-[10px] leading-5 text-white">{unread>99?'۹۹+':unread.toLocaleString('fa-IR')}</span>}</button>{open&&<div id="notification-popover" role="region" aria-label="اعلان‌های اخیر" className="fixed inset-x-4 top-36 z-50 max-h-[calc(100dvh-11rem)] overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-xl sm:absolute sm:inset-x-auto sm:left-0 sm:top-14 sm:w-80"><div className="flex items-center justify-between border-b bg-slate-50 p-4"><strong className="text-sm">اعلان‌های شما</strong><button onClick={()=>setOpen(false)} className="text-sm text-slate-500" aria-label="بستن اعلان‌ها">بستن</button></div>{failed?<p role="status" className="p-4 text-sm text-rose-700">اعلان‌ها دریافت نشد؛ صفحهٔ اعلان‌ها را باز کنید.</p>:unread===null?<div className="p-5" role="status"><Spinner small/><span className="sr-only">دریافت اعلان‌ها</span></div>:items.length?items.map(item=><Link onClick={()=>setOpen(false)} key={item.id} href="/notifications" className={`block border-b border-slate-100 p-4 text-sm leading-6 hover:bg-indigo-50 ${item.readAt?'text-slate-500':'font-semibold text-indigo-900'}`}>{!item.readAt&&<span className="me-2 inline-block h-2 w-2 rounded-full bg-indigo-500"/>}{item.title}</Link>):<p className="p-5 text-sm text-slate-500">هنوز اعلانی ندارید.</p>}<Link onClick={()=>setOpen(false)} href="/notifications" className="block bg-indigo-50 p-3 text-center text-sm font-semibold text-indigo-700">مشاهدهٔ همهٔ اعلان‌ها</Link></div>}</div>;
}
