import Link from 'next/link';
import {redirect} from 'next/navigation';
import {communicationActor,pageNumber} from '@/lib/communication';
import {prisma} from '@/lib/prisma';
import {NotificationRead} from '@/components/communication/notification-controls';
export default async function Notifications({searchParams}:{searchParams:Promise<{unread?:string;page?:string}>}){
 const actor=await communicationActor();if(!actor)redirect('/login');const query=await searchParams;const unread=query.unread==='1';const where={userId:actor.userId,...(unread?{readAt:null}:{})};
 const count=await prisma.notification.count({where});const pages=Math.max(1,Math.ceil(count/20));const page=Math.min(pageNumber(query.page),pages);
 const rows=await prisma.notification.findMany({where,orderBy:[{createdAt:'desc'},{id:'desc'}],skip:(page-1)*20,take:20});
 return <main className="mx-auto max-w-5xl px-4 py-8"><div className="flex flex-wrap items-center justify-between gap-4"><h1 className="text-2xl font-bold">اعلان‌های من</h1><NotificationRead/></div><nav className="my-6 flex gap-2" aria-label="فیلتر اعلان‌ها">{[['0','همه'],['1','خوانده‌نشده']].map(([value,label])=><Link key={value} scroll={false} href={`?unread=${value}`} aria-current={unread===(value==='1')?'page':undefined} className={`panel-action ${unread===(value==='1')?'panel-action-primary':'panel-action-slate'}`}>{label}</Link>)}</nav><div className="space-y-4">{rows.map(n=><article key={n.id} className={`rounded-2xl border bg-white p-5 ${n.readAt?'border-slate-200':'border-indigo-200'}`}><div className="flex items-start justify-between gap-4"><h2 className="break-words font-bold">{n.title}</h2>{!n.readAt&&<span className="shrink-0 rounded-full bg-indigo-50 px-3 py-1 text-xs text-indigo-700">جدید</span>}</div><p className="my-4 whitespace-pre-wrap break-words text-sm leading-8 text-slate-600">{n.body}</p><div className="flex flex-wrap items-center justify-between gap-4"><time className="text-xs text-slate-500">{n.createdAt.toLocaleString('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'})}</time>{!n.readAt?<NotificationRead id={n.id} href={n.href==='/notifications'?undefined:n.href}/>:n.href!=='/notifications'&&<Link className="panel-action" href={n.href}>مشاهدهٔ جزئیات</Link>}</div></article>)}</div>{!rows.length&&<p className="rounded-2xl border bg-white p-8 text-sm text-slate-500">اعلانی در این فهرست وجود ندارد.</p>}<nav className="mt-6 flex items-center justify-center gap-3">{page>1&&<Link scroll={false} className="panel-action panel-action-slate" href={`?unread=${unread?'1':'0'}&page=${page-1}`}>قبل</Link>}<span className="text-sm">{page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span>{page<pages&&<Link scroll={false} className="panel-action panel-action-slate" href={`?unread=${unread?'1':'0'}&page=${page+1}`}>بعد</Link>}</nav></main>;
}
