const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/')?load(n.slice(2)+(fs.existsSync(path.join(__dirname,'..',n.slice(2)+'.tsx'))?'.tsx':'.ts'),mocks):require(n),m,m.exports);return m.exports;}

const designs=load('lib/certificate-templates.ts');
test('legacy certificate uses default design; unsafe CSS is rejected',()=>{assert.equal(designs.certificateDesign(null).style,'CLASSIC');assert.equal(designs.templateInput.safeParse({...designs.defaultDesign,accent:'url(https://bad)'}).success,false);for(const style of ['CLASSIC','MODERN','KIDS'])assert.equal(designs.certificateDesign({...designs.defaultDesign,style}).style,style);});
test('test sessions require development AND explicit opt-in',()=>{const oldNode=process.env.NODE_ENV,oldFlag=process.env.DEV_TEST_USERS_ENABLED;const policy=load('lib/dev-test-policy.ts');try{for(const mode of ['production','test','development'])for(const flag of ['false','true']){process.env.NODE_ENV=mode;process.env.DEV_TEST_USERS_ENABLED=flag;assert.equal(policy.allowTestSession(true),mode==='development'&&flag==='true');assert.equal(policy.allowTestSession(false),true);}}finally{if(oldNode===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=oldNode;if(oldFlag===undefined)delete process.env.DEV_TEST_USERS_ENABLED;else process.env.DEV_TEST_USERS_ENABLED=oldFlag;}});
function ownerSetup({enabled=true,current={userId:'s',role:'STUDENT',testMode:true},original={userId:'a',role:'ADMIN'},studentOwner='a',adminRole='ADMIN'}={}){let calls=0;return {api:load('lib/dev-test-accounts.ts',{'@/lib/dev-test-policy':{devTestingEnabled:()=>enabled},'next/headers':{cookies:async()=>({get:n=>({value:n==='session'?'current':'original'})})},'@/lib/auth':{verifySession:async t=>t==='current'?current:original},'@/lib/prisma':{prisma:{user:{findUnique:async({where})=>{calls++;return where.id==='s'?{id:'s',role:'STUDENT',testOwnerId:studentOwner}: {id:where.id,role:adminRole};}}}}}),get calls(){return calls}};}
test('test account restores only its still-authorized original admin',async()=>{assert.deepEqual(await ownerSetup().api.devTestOwner(),{id:'a',token:'original'});for(const args of [{studentOwner:'other'},{adminRole:'STUDENT'},{original:null},{current:{userId:'s',role:'ADMIN',testMode:true}},{original:{userId:'a',role:'ADMIN',testMode:true}}])assert.equal(await ownerSetup(args).api.devTestOwner(),null);});
test('disabled test tool does not inspect cookies or database',async()=>{const s=ownerSetup({enabled:false});assert.equal(await s.api.devTestOwner(),null);assert.equal(s.calls,0);});
test('switch endpoint denies users outside the original admin scope',async()=>{const {NextRequest}=require('next/server');let scope;const api=load('app/api/dev/test-users/route.ts',{'@/lib/dev-test-policy':{devTestingEnabled:()=>true},'@/lib/dev-test-accounts':{devTestOwner:async()=>({id:'a',token:'original'})},'@/lib/auth':{createSession:()=>assert.fail('must not sign')},'@/lib/prisma':{prisma:{user:{findFirst:async q=>{scope=q.where;return null;}}}}});const req=new NextRequest('http://localhost/api/dev/test-users',{method:'POST',headers:{origin:'http://localhost'},body:JSON.stringify({action:'switch',userId:'real'})});assert.equal((await api.POST(req)).status,403);assert.equal(scope.testOwnerId,'a');assert.deepEqual(scope.role.in,['TEACHER','STUDENT']);});
