const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/')?load(n.slice(2)+(fs.existsSync(path.join(__dirname,'..',n.slice(2)+'.tsx'))?'.tsx':'.ts'),mocks):require(n),m,m.exports);return m.exports;}
test('OTP accepts Persian and Arabic digits and removes non-digits',()=>{const {otpDigits}=load('components/ui/otp-input.tsx');assert.equal(otpDigits('۱٢3 ۴۵۶'),'123456');});
function queue(){const course={id:'c',title:'نمونه',slug:'sample',status:'PUBLISHED',deliveryStatus:'ONGOING',launchSmsPending:false};const jobs=[];const tx={course:{findUniqueOrThrow:async()=>course,update:async({data})=>Object.assign(course,data)},courseInterest:{findMany:async()=>[{id:'i',phone:'09123456789'}]},courseStartSms:{createMany:async({data,skipDuplicates})=>{assert.ok(skipDuplicates);let count=0;for(const job of data)if(!jobs.some(j=>j.interestId===job.interestId)){jobs.push(job);count++;}return {count};}}};const api=load('lib/course-start-sms.ts',{'@/lib/prisma':{prisma:{}},'@/lib/sms':{sendSms:()=>assert.fail('queue cannot send')}});return {api,tx,course,jobs};}
test('launch queues once per preregistration and ordinary course edits do not queue',async()=>{const s=queue();assert.equal(await s.api.queueCourseStart(s.tx,'c','ONGOING'),0);assert.equal(await s.api.queueCourseStart(s.tx,'c','UPCOMING'),1);assert.equal(await s.api.queueCourseStart(s.tx,'c','UPCOMING'),0);assert.equal(s.jobs.length,1);});
test('starting a draft defers SMS until publication',async()=>{const s=queue();s.course.status='DRAFT';assert.equal(await s.api.queueCourseStart(s.tx,'c','UPCOMING'),0);assert.equal(s.course.launchSmsPending,true);s.course.status='PUBLISHED';assert.equal(await s.api.queueCourseStart(s.tx,'c'),1);assert.equal(s.course.launchSmsPending,false);});
test('worker claims only pending published ongoing courses and records provider acceptance',async()=>{process.env.FARAZ_SMS_API_KEY='fake';process.env.FARAZ_SMS_LINE_NUMBER='fake';const job={id:'j',phone:'09123456789',message:'شروع',interest:{course:{title:'دوره',slug:'c'}}};let queryCount=0,sent=0,updates=[];const tx={$queryRaw:async(strings)=>{assert.match(strings.join(''),/SKIP LOCKED/);assert.match(strings.join(''),/PUBLISHED/);return queryCount++===0?[{id:'j'}]:[];},courseStartSms:{update:async q=>{updates.push(q.data);return job;}}};const api=load('lib/course-start-sms.ts',{'@/lib/prisma':{prisma:{...tx,$transaction:fn=>fn(tx),courseStartSms:{...tx.courseStartSms,updateMany:async()=>{}}}},'@/lib/sms':{sendSms:async()=>{sent++;return {status:'success'};}}});assert.equal((await api.processCourseStartSms('c')).processed,1);assert.equal(sent,1);assert.equal(updates[0].status,'SENDING');assert.equal(updates[1].status,'SENT');delete process.env.FARAZ_SMS_API_KEY;delete process.env.FARAZ_SMS_LINE_NUMBER;});
test('missing SMS configuration leaves queue untouched',async()=>{const api=load('lib/course-start-sms.ts',{'@/lib/prisma':{prisma:{$transaction:()=>assert.fail('no claim')}},'@/lib/sms':{sendSms:()=>assert.fail('no send')}});assert.equal((await api.processCourseStartSms()).configured,false);});
test('catalog ribbon is based on own active/completed enrollment, not another account',async()=>{let where;const Page=load('app/courses/page.tsx',{'@/lib/auth':{getSession:async()=>({userId:'student',role:'STUDENT'})},'@/lib/prisma':{prisma:{course:{findMany:async()=>[{id:'c',slug:'course',title:'دوره',teacherId:'teacher',teacher:{name:'مدرس'},price:0,discountPercent:0,deliveryStatus:'ONGOING'}]},enrollment:{findMany:async(q)=>{where=q.where;return [{courseId:'c'}];}}}},'next/link':{default:({children,...p})=>React.createElement('a',p,children)}}).default;const html=renderToStaticMarkup(await Page());assert.match(html,/ثبت‌نام شده/);assert.equal(where.userId,'student');assert.deepEqual(where.status.in,['ACTIVE','COMPLETED']);});
test('SMS processing rejects guest before reading course or contacting provider',async()=>{const route=load('app/api/courses/[courseId]/start-sms/route.ts',{'@/lib/management-session':{getManagementSession:async()=>null},'@/lib/prisma':{prisma:{}},'@/lib/course-start-sms':{processCourseStartSms:()=>assert.fail('no send')}});assert.equal((await route.POST(new Request('http://test',{method:'POST'}),{params:Promise.resolve({courseId:'c'})})).status,401);});
test('ambiguous SMS errors are recorded without automatic resend',async()=>{process.env.FARAZ_SMS_API_KEY='fake';process.env.FARAZ_SMS_LINE_NUMBER='fake';let claims=0,status='PENDING',sent=0;const job={id:'j',phone:'09123456789',message:'متن',interest:{course:{title:'دوره'}}};const tx={$queryRaw:async()=>claims++===0?[{id:'j'}]:[],courseStartSms:{update:async({data})=>{status=data.status;return job;},updateMany:async()=>{}}};const api=load('lib/course-start-sms.ts',{'@/lib/prisma':{prisma:{...tx,$transaction:fn=>fn(tx)}},'@/lib/sms':{sendSms:async()=>{sent++;throw Error('timeout')}}});await api.processCourseStartSms();assert.equal(status,'UNKNOWN');await api.processCourseStartSms();assert.equal(sent,1);delete process.env.FARAZ_SMS_API_KEY;delete process.env.FARAZ_SMS_LINE_NUMBER;});
