const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function load(file,mocks={}){const module={exports:{}};const source=fs.readFileSync(path.join(__dirname,'..',file),'utf8');const out=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','module','exports',out)(name=>{if(name in mocks)return mocks[name];if(name.startsWith('@/')){const b=name.slice(2);return load(b+(fs.existsSync(path.join(__dirname,'..',b+'.tsx'))?'.tsx':'.ts'),mocks)}return require(name)},module,module.exports);return module.exports;}
const student={id:'student',role:'STUDENT'},teacher={id:'teacher',role:'TEACHER'},admin={id:'admin',role:'ADMIN'},outsider={id:'other',role:'TEACHER'};
const examInput={title:'آزمون نهایی',instructions:'راهنمای آزمون',questions:['سؤال اول چیست؟'],published:true,version:1,examWeight:50};
function setup(){
 const state={course:{id:'course',teacherId:'teacher',status:'PUBLISHED',title:'دوره'},enrollment:{id:'enroll',userId:'student',courseId:'course',status:'COMPLETED'},exam:{id:'exam',courseId:'course',...examInput,_count:{attempts:0}},attempt:null,lessons:[{id:'lesson',videoUrl:'video'}],progress:[{lessonId:'lesson',status:'COMPLETED',videoCompletedAt:new Date()}],writes:[],notices:[],notes:[]};
 const tx={$queryRaw:async()=>{},course:{findUnique:async()=>state.course},enrollment:{findUnique:async()=>state.enrollment?{...state.enrollment,course:state.course,examAttempt:state.attempt}:null},lesson:{findMany:async()=>state.lessons},lessonProgress:{findMany:async()=>state.progress},finalExam:{findUnique:async()=>state.exam,upsert:async({create,update})=>{state.writes.push({create,update});return {...state.exam,version:2};}},examAttempt:{findUnique:async()=>state.attempt,create:async({data})=>{state.writes.push(data);state.attempt={id:'attempt',score:null,...data};return state.attempt;},update:async({data})=>{state.writes.push(data);state.attempt={...state.attempt,...data};return state.attempt;}},finalFeedback:{upsert:async(data)=>{state.notes.push(data);return {id:'note'};}},courseReview:{upsert:async({create,update})=>{state.writes.push({create,update});return {id:'review'};}}};
 const prisma={...tx,$transaction:fn=>fn(tx)};const notices={notifyUsers:async(_tx,users,notice)=>state.notices.push({users,...notice}),notifyCourse:async(_tx,courseId,notice)=>state.notices.push({courseId,...notice})};
 return {state,tx,prisma,api:load('lib/final-assessment.ts',{'@/lib/prisma':{prisma},'@/lib/notifications':notices})};
}
test('final mark waits for exam and every assignment, preserving zero scores',()=>{const {api}=setup();assert.equal(api.finalMark(null,[100],50),null);assert.equal(api.finalMark(80,[null],50),null);assert.equal(api.finalMark(80,[60,100],50),80);assert.equal(api.finalMark(0,[0],50),0);assert.equal(api.finalMark(75,[],0),75);assert.equal(api.finalMark(90,[60,80],30),76);});
for(const actor of [student,outsider])test(`${actor.role}/${actor.id} cannot edit a teacher's final exam`,async()=>{const {api,state}=setup();await assert.rejects(api.saveExam(actor,'course',examInput),/اجازه/);assert.equal(state.writes.length,0)});
test('owner saves exam and notifies enrolled learners',async()=>{const {api,state}=setup();await api.saveExam(teacher,'course',examInput);assert.equal(state.notices[0].courseId,'course');assert.equal(state.writes[0].update.version.increment,1)});
test('admin can manage exam but stale version and attempts freeze edits',async()=>{const {api,state}=setup();await api.saveExam(admin,'course',examInput);state.exam.version=2;await assert.rejects(api.saveExam(admin,'course',examInput),/تغییر/);state.exam._count.attempts=1;await assert.rejects(api.saveExam(admin,'course',{...examInput,version:2}),/ثابت/)});
for(const kind of ['empty','not-completed','video-not-watched'])test(`exam rejects incomplete curriculum: ${kind}`,async()=>{const {api,state}=setup();if(kind==='empty')state.lessons=[];if(kind==='not-completed')state.progress[0].status='IN_PROGRESS';if(kind==='video-not-watched')state.progress[0].videoCompletedAt=null;await assert.rejects(api.submitExam(student,'course',{version:1,answers:['پاسخ']}),/تکمیل/);assert.equal(state.writes.length,0)});
test('completed text-only lesson does not require a video timestamp',async()=>{const {api,state}=setup();state.lessons[0].videoUrl=null;state.progress[0].videoCompletedAt=null;await api.submitExam(student,'course',{version:1,answers:['پاسخ']});assert.equal(state.writes.length,1)});
for(const kind of ['no-enrollment','cancelled','unpublished','admin','owner'])test(`exam submission refuses ${kind}`,async()=>{const {api,state}=setup();if(kind==='no-enrollment')state.enrollment=null;if(kind==='cancelled')state.enrollment.status='CANCELLED';if(kind==='unpublished')state.course.status='DRAFT';const actor=kind==='admin'?admin:kind==='owner'?teacher:student;await assert.rejects(api.submitExam(actor,'course',{version:1,answers:['پاسخ']}),/ثبت‌نام/);assert.equal(state.writes.length,0)});
test('exam requires published current version and exactly one answer per question',async()=>{const {api,state}=setup();state.exam.published=false;await assert.rejects(api.submitExam(student,'course',{version:1,answers:['a']}));state.exam.published=true;await assert.rejects(api.submitExam(student,'course',{version:2,answers:['a']}));await assert.rejects(api.submitExam(student,'course',{version:1,answers:['a','b']}));assert.equal(state.writes.length,0)});
test('retry preserves original exam answer and sends no duplicate notification',async()=>{const {api,state}=setup();await api.submitExam(student,'course',{version:1,answers:['اول']});await api.submitExam(student,'course',{version:1,answers:['دوم']});assert.equal(state.writes.length,1);assert.deepEqual(state.attempt.answers,['اول']);assert.equal(state.notices.length,1);assert.deepEqual(state.notices[0].users,['teacher'])});
test('enrollment cancelled while waiting for lock cannot submit',async()=>{const {api,tx,state}=setup();tx.$queryRaw=async strings=>{if(strings[0].includes('Enrollment'))state.enrollment.status='CANCELLED'};await assert.rejects(api.submitExam(student,'course',{version:1,answers:['a']}),/فعال/);assert.equal(state.writes.length,0)});
for(const actor of [student,outsider])test(`grading is denied to ${actor.id}`,async()=>{const {api,state}=setup();state.attempt={id:'attempt'};await assert.rejects(api.gradeExam(actor,'enroll',{score:90,feedback:'بازخورد'}));assert.equal(state.writes.length,0)});
test('grade stores reviewer and score once and notifies only learner',async()=>{const {api,state}=setup();state.attempt={id:'attempt',score:null};await api.gradeExam(teacher,'enroll',{score:0,feedback:'بازخورد آزمون'});assert.equal(state.attempt.score,0);assert.equal(state.attempt.reviewedBy,'teacher');assert.deepEqual(state.notices[0].users,['student']);await assert.rejects(api.gradeExam(admin,'enroll',{score:100,feedback:'اصلاح نمره'}),/قبلاً/)});
test('each role updates only its own report feedback field',async()=>{const {api,state}=setup();await api.saveFinalNote(teacher,'enroll',{note:'بازخورد مدرس',adminNote:'forged'});await api.saveFinalNote(admin,'enroll',{note:'بازخورد مدیر',teacherNote:'forged'});assert.equal(state.notes[0].update.adminNote,undefined);assert.equal(state.notes[1].update.teacherNote,undefined);assert.equal(state.notes[0].update.teacherNote,'بازخورد مدرس');await assert.rejects(api.saveFinalNote(outsider,'enroll',{note:'متن'}))});
test('course review requires completed lessons and records parent declaration in learner enrollment',async()=>{const {api,state}=setup();state.progress=[];await assert.rejects(api.saveCourseReview(student,'course',{authorType:'PARENT',rating:5,body:'دورهٔ خوبی بود'}));state.progress=[{lessonId:'lesson',status:'COMPLETED',videoCompletedAt:new Date()}];await api.saveCourseReview(student,'course',{authorType:'PARENT',rating:4,body:'دورهٔ خوبی بود'});assert.equal(state.writes[0].create.enrollmentId,'enroll');assert.equal(state.writes[0].create.authorType,'PARENT')});
test('schemas reject out of range scores, weight and review rating',()=>{const {api}=setup();assert.equal(api.gradeInput.safeParse({score:101,feedback:'متن'}).success,false);assert.equal(api.examInput.safeParse({...examInput,examWeight:-1}).success,false);assert.equal(api.courseReviewInput.safeParse({authorType:'ADMIN',rating:6,body:'نظر کاربر'}).success,false)});
test('report does not query grades for an unrelated teacher or student',async()=>{for(const actor of [outsider,{id:'other-student',role:'STUDENT'}]){const s=setup();const Report=load('components/assessment/final-report.tsx',{'@/lib/assignment-api':{assignmentActor:async()=>actor},'@/lib/prisma':{prisma:s.prisma}}).default;assert.equal(await Report({enrollmentId:'enroll'}),null)}});
test('exam gateway reveals start link only after completion and publication',async()=>{const s=setup();const mocks={'@/lib/assignment-api':{assignmentActor:async()=>student},'@/lib/prisma':{prisma:s.prisma},'next/link':{default:({children,...props})=>React.createElement('a',props,children)}};const Gateway=load('components/assessment/exam-gateway.tsx',mocks).default;assert.match(renderToStaticMarkup(await Gateway({courseId:'course'})),/شروع آزمون پایانی/);s.state.progress=[];assert.doesNotMatch(renderToStaticMarkup(await Gateway({courseId:'course'})),/شروع آزمون پایانی/);s.state.enrollment.status='CANCELLED';assert.equal(await Gateway({courseId:'course'}),null)});
test('notification icons distinguish money, tickets, exams and lessons',()=>{const {relatedIcon}=load('components/panel/theme-icon.tsx');assert.equal(relatedIcon('ticket:created'),'message');assert.equal(relatedIcon('exam-grade:attempt'),'award');assert.equal(relatedIcon('payout:paid'),'wallet');assert.equal(relatedIcon('lesson:published'),'book')});
for(const route of ['courses/[courseId]/exam','courses/[courseId]/exam/submit','courses/[courseId]/review','enrollments/[enrollmentId]/exam-grade','enrollments/[enrollmentId]/final-note'])test(`guest rejected by ${route}`,async()=>{const api=load(`app/api/${route}/route.ts`,{'@/lib/assignment-api':{assignmentActor:async()=>null}});const handler=api.POST||api.PUT;assert.equal((await handler(new Request('http://test'),{params:Promise.resolve({courseId:'course',enrollmentId:'enroll'})})).status,401)});
test('student exam page does not fetch questions when completion is missing',async()=>{const s=setup();s.state.progress=[];s.prisma.finalExam.findFirst=async()=>assert.fail('locked questions must not be queried');const Page=load('app/dashboard/courses/[courseId]/exam/page.tsx',{'@/lib/assignment-api':{assignmentActor:async()=>student},'@/lib/prisma':{prisma:s.prisma},'next/link':{default:({children,...props})=>React.createElement('a',props,children)}}).default;const html=renderToStaticMarkup(await Page({params:Promise.resolve({courseId:'course'})}));assert.match(html,/آزمون هنوز در دسترس نیست/);assert.doesNotMatch(html,/سؤال اول/)});
test('final report shows separate instructor and admin feedback and weighted score',async()=>{const s=setup();s.state.course.finalExam={examWeight:50};s.state.attempt={score:80,feedback:'ارزیابی آزمون'};s.prisma.enrollment.findUnique=async()=>({...s.state.enrollment,course:s.state.course,examAttempt:s.state.attempt,finalFeedback:{teacherNote:'پیام ویژهٔ مدرس',adminNote:'پیام ویژهٔ مدیر'},courseReview:null});s.prisma.assignment={findMany:async()=>[{id:'a',title:'تمرین',submissions:[{status:'GRADED',score:60}]}]};const Report=load('components/assessment/final-report.tsx',{'@/lib/assignment-api':{assignmentActor:async()=>student},'@/lib/prisma':{prisma:s.prisma},'@/components/assessment/forms':{FinalNote:()=>null,ReviewForm:()=>null}}).default;let html=renderToStaticMarkup(await Report({enrollmentId:'enroll'}));assert.match(html,/۷۰ از ۱۰۰/);assert.match(html,/پیام ویژهٔ مدرس/);assert.match(html,/پیام ویژهٔ مدیر/);s.prisma.assignment.findMany=async()=>[{id:'a',title:'تمرین',submissions:[]}];html=renderToStaticMarkup(await Report({enrollmentId:'enroll'}));assert.match(html,/هنوز نهایی نشده/);assert.doesNotMatch(html,/۷۰ از ۱۰۰/)});
