const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,mocks={}){const m={exports:{}};new Function('require','module','exports',ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText)(n=>n in mocks?mocks[n]:n.startsWith('@/')?load(n.slice(2)+(fs.existsSync(path.join(__dirname,'..',n.slice(2)+'.tsx'))?'.tsx':'.ts'),mocks):require(n),m,m.exports);return m.exports;}
const req=body=>new Request('http://test/api',{method:'POST',headers:{origin:'http://test','content-type':'application/json'},body:JSON.stringify(body)});
const course={id:'c',price:1000,discountPercent:20,teacherId:'t',status:'PUBLISHED',deliveryStatus:'ONGOING',slug:'course'};
const coupons=load('lib/coupons.ts');
test('coupon is normalized and calculated after advertised discount',()=>{assert.equal(coupons.couponCode(' spring-20 '),'SPRING-20');assert.deepEqual(coupons.couponPrice(course,{active:true,courseId:'c',percent:25},'X'),{base:800,percent:25,amount:600});});
for(const invalid of [null,{active:false,courseId:null,percent:10},{active:true,courseId:'other',percent:10},{active:true,courseId:null,percent:101}])test('invalid coupon is rejected '+JSON.stringify(invalid),()=>assert.throws(()=>coupons.couponPrice(course,invalid,'CODE')));
test('100 percent coupon gives zero and absence of code preserves advertised price',()=>{assert.equal(coupons.couponPrice(course,{active:true,courseId:null,percent:100},'FREE').amount,0);assert.equal(coupons.couponPrice(course,null,'').amount,800);});
for(const role of ['STUDENT','TEACHER'])test('non-admin cannot send course SMS: '+role,async()=>{const api=load('app/api/courses/[courseId]/start-sms/route.ts',{'@/lib/management-session':{getManagementSession:async()=>({userId:'t',role})},'@/lib/prisma':{prisma:{course:{findUnique:async()=>course}}},'@/lib/course-start-sms':{processCourseStartSms:()=>assert.fail('no send')}});assert.equal((await api.POST(req({prepare:true}),{params:Promise.resolve({courseId:'c'})})).status,403);});
for(const route of ['sms','coupons','certificates'])test('admin mutation rejects a student: '+route,async()=>{const api=load(`app/api/admin/${route}/route.ts`,{'@/lib/management-session':{getManagementSession:async()=>({userId:'s',role:'STUDENT'})},'@/lib/prisma':{prisma:{}},'@/lib/manual-sms':{},'@/lib/notifications':{}});assert.equal((await api.POST(req({}))).status,403);});
test('manual course preparation includes coupon and preserves sent messages',async()=>{let data;const tx={$queryRaw:async()=>{},course:{findUniqueOrThrow:async()=>({...course,title:'دوره'})},discountCode:{findUnique:async()=>({code:'START',active:true,courseId:'c',percent:30})},courseInterest:{findMany:async()=>[{id:'i',phone:'09123456789'}]},courseStartSms:{createMany:async x=>{data=x;return {count:1};}}};const api=load('lib/course-start-sms.ts',{'@/lib/prisma':{prisma:{}},'@/lib/sms':{},'@/lib/notifications':{}});await api.prepareCourseStart(tx,'c','START');assert.equal(data.skipDuplicates,true);assert.match(data.data[0].message,/START/);assert.match(data.data[0].message,/30/);});
test('broadcast snapshots normalized unique numbers and excludes test accounts',async()=>{let scope,deliveries;const tx={$executeRaw:async(strings)=>{assert.match(strings.join(''),/pg_advisory_xact_lock/);return 1;},$queryRaw:async()=>assert.fail('advisory lock must use executeRaw'),smsCampaign:{findUnique:async()=>null,create:async({data})=>data},user:{findMany:async({where})=>{scope=where;return [{phone:'09123456789'},{phone:'+989123456789'},{phone:'bad'}];}},smsDelivery:{createMany:async({data})=>{deliveries=data;}}};const api=load('lib/manual-sms.ts',{'@/lib/prisma':{prisma:{$transaction:fn=>fn(tx)}},'@/lib/sms':{}});await api.createCampaign('admin',{requestId:'00000000-0000-4000-8000-000000000000',audience:'TEACHER',message:'پیام نمونه',variables:{}});assert.equal(scope.role,'TEACHER');assert.equal(scope.demoBatchId,null);assert.equal(deliveries.length,1);assert.equal(deliveries[0].phone,'09123456789');});
test('SMS timeout is persisted as UNKNOWN and is never blindly retried',async()=>{process.env.FARAZ_SMS_API_KEY='test';process.env.FARAZ_SMS_LINE_NUMBER='test';let claimed=false,status,calls=0;const tx={$queryRaw:async()=>{if(claimed)return [];claimed=true;return [{id:'d'}];},smsDelivery:{update:async({data})=>{status=data.status;return {id:'d',phone:'09123456789'};},updateMany:async()=>{}}};const db={...tx,smsCampaign:{findUniqueOrThrow:async()=>({message:'hello'})},$transaction:fn=>fn(tx)};const api=load('lib/manual-sms.ts',{'@/lib/prisma':{prisma:db},'@/lib/sms':{sendSms:async()=>{calls++;throw Error('timeout');}}});try{await api.processCampaign('c');assert.equal(status,'UNKNOWN');await api.processCampaign('c');assert.equal(calls,1);}finally{delete process.env.FARAZ_SMS_API_KEY;delete process.env.FARAZ_SMS_LINE_NUMBER;}});
function certSetup(){let issued=0,notice=0;const enrollment={id:'e',courseId:'c',userId:'s',status:'ACTIVE',user:{name:'دانش‌آموز',role:'STUDENT'},course:{...course,title:'دوره',finalExam:{published:true,examWeight:50}},examAttempt:{score:80},certificate:null};const tx={$queryRaw:async()=>{},enrollment:{findUnique:async()=>enrollment,findUniqueOrThrow:async()=>enrollment},lesson:{findMany:async()=>[{id:'l',videoUrl:'video'}]},lessonProgress:{findMany:async()=>[{lessonId:'l',status:'COMPLETED',videoCompletedAt:new Date()}]},assignment:{findMany:async()=>[{submissions:[{status:'GRADED',score:60}]}]},certificate:{create:async({data})=>{issued++;return enrollment.certificate={id:'cert',...data};}}};const api=load('lib/certificates.ts',{'@/lib/prisma':{prisma:{$transaction:fn=>fn(tx)}},'@/lib/notifications':{notifyUsers:async()=>{notice++;}}});return {enrollment,tx,api,get issued(){return issued},get notice(){return notice}};}
test('certificate has immutable score snapshot and issuance is idempotent',async()=>{const s=certSetup();const cert=await s.api.issueCertificate({id:'s',role:'STUDENT'},'e');assert.equal(cert.score,70);assert.equal(cert.studentName,'دانش‌آموز');s.enrollment.examAttempt.score=100;assert.equal((await s.api.issueCertificate({id:'s',role:'STUDENT'},'e')).score,70);assert.equal(s.issued,1);assert.equal(s.notice,1);});
for(const scenario of ['otherStudent','otherTeacher','cancelled','missingGrade','incompleteVideo','failedExam','revoked'])test('certificate rejects '+scenario,async()=>{const s=certSetup();let actor={id:'s',role:'STUDENT'};if(scenario==='otherStudent')actor.id='other';if(scenario==='otherTeacher')actor={id:'other',role:'TEACHER'};if(scenario==='cancelled')s.enrollment.status='CANCELLED';if(scenario==='missingGrade')s.tx.assignment.findMany=async()=>[{submissions:[]}];if(scenario==='incompleteVideo')s.tx.lessonProgress.findMany=async()=>[{lessonId:'l',status:'COMPLETED',videoCompletedAt:null}];if(scenario==='failedExam')s.enrollment.examAttempt.score=50;if(scenario==='revoked')s.enrollment.certificate={revokedAt:new Date()};await assert.rejects(s.api.issueCertificate(actor,'e'));assert.equal(s.issued,0);});
test('cancelled enrollments and revoked certificates fail public validation',()=>{const s=certSetup();assert.equal(s.api.certificateValid({revokedAt:null,enrollment:{status:'ACTIVE'}}),true);assert.equal(s.api.certificateValid({revokedAt:new Date(),enrollment:{status:'ACTIVE'}}),false);assert.equal(s.api.certificateValid({revokedAt:null,enrollment:{status:'CANCELLED'}}),false);});
test('new user name endpoint updates only blank names, never role or existing names',async()=>{let update;const api=load('app/api/auth/name/route.ts',{'@/lib/management-session':{getManagementSession:async()=>({userId:'s',role:'STUDENT'})},'@/lib/prisma':{prisma:{user:{updateMany:async q=>{update=q;}}}}});assert.equal((await api.POST(req({name:'نام من',role:'ADMIN'}))).status,200);assert.deepEqual(update.data,{name:'نام من'});assert.equal(update.where.id,'s');assert.deepEqual(update.where.OR,[{name:null},{name:''}]);assert.equal((await api.POST(req({name:'x'}))).status,400);});
test('100 percent checkout records zero revenue and never calls gateway',async()=>{let receipt,enrolled=0;const tx={$queryRaw:async()=>{},enrollment:{findUnique:async()=>null,upsert:async()=>{enrolled++;}},payment:{create:async({data})=>{receipt=data;}}};const db={...tx,$transaction:fn=>fn(tx),course:{findUnique:async()=>course},discountCode:{findUnique:async()=>({active:true,courseId:'c',percent:100})}};const api=load('app/api/payments/create/route.ts',{'@/lib/management-session':{getManagementSession:async()=>({userId:'s',role:'STUDENT'})},'@/lib/prisma':{prisma:db},'@/lib/zarinpal':{requestPayment:()=>assert.fail('no gateway')}});assert.equal((await api.POST(req({courseId:'c',code:'FREE',amount:9000}))).status,200);assert.equal(enrolled,1);assert.equal(receipt.amount,0);assert.equal(receipt.teacherShareAmount,0);assert.equal(receipt.couponCode,'FREE');});

test('certificate saves a detached template snapshot and retains it after edits',async()=>{const s=certSetup();s.enrollment.course.certificateTemplate={name:'قالب اول',style:'MODERN',accent:'#123456',issuer:'آموزش',issuerEn:'School',signatory:'مدیر',active:true};const c=await s.api.issueCertificate({id:'s',role:'STUDENT'},'e');s.enrollment.course.certificateTemplate.accent='#ffffff';assert.equal(c.templateSnapshot.accent,'#123456');assert.equal(c.isTest,false);assert.equal((await s.api.issueCertificate({id:'s',role:'STUDENT'},'e')).templateSnapshot.accent,'#123456');});
test('inactive assigned certificate template blocks new issuance',async()=>{const s=certSetup();s.enrollment.course.certificateTemplate={active:false};await assert.rejects(s.api.issueCertificate({id:'s',role:'STUDENT'},'e'),/قالب/);assert.equal(s.issued,0);});
