const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
function load(file,mocks={}){const module={exports:{}};const out=ts.transpileModule(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','module','exports',out)(n=>n in mocks?mocks[n]:n.startsWith('@/')?load(n.slice(2)+(fs.existsSync(path.join(__dirname,'..',n.slice(2)+'.tsx'))?'.tsx':'.ts'),mocks):require(n),module,module.exports);return module.exports;}
process.env.AUTH_SECRET='test-secret-not-real';
const policy=load('lib/otp-policy.ts');
test('phone normalization supports Persian digits and international Iranian prefix',()=>{for(const p of ['۰۹۱۲۳۴۵۶۷۸۹','+989123456789','00989123456789','989123456789'])assert.equal(policy.normalizePhone(p),'09123456789');for(const p of ['0912','+12025550123',null])assert.throws(()=>policy.normalizePhone(p));});
test('OTP digest binds code to phone and challenge and redirects stay local',()=>{const d=policy.otpDigest('p','a','123456');assert.equal(policy.matchesOtp(d,policy.otpDigest('p','a','123456')),true);assert.equal(policy.matchesOtp(d,policy.otpDigest('p','b','123456')),false);for(const v of ['//evil.test','/\\evil.test','https://evil.test'])assert.equal(policy.safeRedirect(v,'/dashboard'),'/dashboard');});
function setup(){
 let row=null,bucket=null,users=[],sent=[],sendFail=false;
 const apply=(base,data)=>{for(const [k,v] of Object.entries(data))base[k]=v&&typeof v==='object'&&'increment'in v?(base[k]||0)+v.increment:v;return base;};
 const tx={$executeRaw:async(strings)=>{assert.match(strings.join(''),/pg_advisory_xact_lock/);return 1;},$queryRaw:async()=>assert.fail('OTP advisory lock must not deserialize void'),otpRateBucket:{findUnique:async()=>bucket,upsert:async({create,update})=>bucket=bucket?apply(bucket,update):create},loginOtp:{findUnique:async({where})=>row&&(!where.challengeId||row.challengeId===where.challengeId)?row:null,upsert:async({create})=>row??(row={...create,attempts:0,consecutiveFailures:0,sentCount:0,windowStart:new Date()}),update:async({data})=>apply(row,data),updateMany:async({where,data})=>{if(row&&(!where.challengeId||where.challengeId===row.challengeId))apply(row,data);}},user:{findMany:async()=>users,create:async({data})=>{const user={id:'new',...data};users.push(user);return user;}}};
 const api=load('lib/login-otp.ts',{'@/lib/prisma':{prisma:{...tx,$transaction:fn=>fn(tx)}},'@/lib/sms':{sendSms:async(p)=>{if(sendFail)throw Error('down');sent.push(p);return {status:'success'};}}});
 return {api,get row(){return row},get users(){return users},set users(v){users=v},sent,fail(){sendFail=true},code(){return sent.at(-1).message.match(/\d{6}/)[0]},cool(){row.lastSentAt=new Date(Date.now()-61000)}};
}
test('OTP is hashed, expires in five minutes, logs in existing role and is single-use',async()=>{const s=setup();s.users=[{id:'teacher',role:'TEACHER',name:'نام قبلی'}];const result=await s.api.requestOtp('09123456789','ip1');assert.ok(new Date(result.expiresAt)-Date.now()>295000);assert.notEqual(s.row.digest,s.code());const ok=await s.api.verifyOtp(result.challengeId,s.code());assert.equal(ok.user.role,'TEACHER');assert.equal(ok.needsName,false);assert.ok((await s.api.verifyOtp(result.challengeId,s.code())).restart);});
test('three wrong answers invalidate challenge; ten across resends block phone',async()=>{const s=setup();let result=await s.api.requestOtp('09123456789','ip1');for(let n=1;n<=10;n++){const bad=await s.api.verifyOtp(result.challengeId,'000000');assert.ok(bad.error);if(n%3===0&&n<10){assert.equal(bad.restart,true);s.cool();result=await s.api.requestOtp('09123456789','ip1');assert.equal(s.row.consecutiveFailures,n);}}assert.ok(s.row.blockedAt);s.cool();await assert.rejects(s.api.requestOtp('09123456789','ip1'),/بلاک/);});
test('expiration cannot create account; correct code resets failure streak',async()=>{const s=setup();let result=await s.api.requestOtp('09123456789','ip1');s.row.expiresAt=new Date(0);assert.ok((await s.api.verifyOtp(result.challengeId,s.code())).restart);assert.equal(s.users.length,0);s.cool();result=await s.api.requestOtp('09123456789','ip1');await s.api.verifyOtp(result.challengeId,'000000');const ok=await s.api.verifyOtp(result.challengeId,s.code());assert.equal(ok.user.role,'STUDENT');assert.equal(ok.needsName,true);assert.equal(s.row.consecutiveFailures,0);});
test('provider error invalidates challenge and resends respect cooldown',async()=>{const s=setup();s.fail();await assert.rejects(s.api.requestOtp('09123456789','ip1'),/ارسال/);assert.equal(s.row.digest,null);assert.equal(s.row.challengeId,null);await assert.rejects(s.api.requestOtp('09123456789','ip1'),/یک دقیقه/);});
test('ambiguous legacy phone accounts are not merged',async()=>{const s=setup();s.users=[{id:'a'},{id:'b'}];const result=await s.api.requestOtp('09123456789','ip1');assert.match((await s.api.verifyOtp(result.challengeId,s.code())).error,/پشتیبانی/);});
test('binary essay grading counts all questions equally and requires exact verdict count',()=>{const q=load('lib/exam-questions.ts');const questions=[{type:'CHOICE',prompt:'گزینه درست؟',options:['a','b','c','d'],correctOption:1},'تشریحی اول','تشریحی دوم'];assert.equal(q.scoreVerdicts(questions,['1','جواب','جواب'],[true,false]),67);assert.equal(q.scoreVerdicts(questions,['0','جواب','جواب'],[false,false]),0);assert.throws(()=>q.scoreVerdicts(questions,['1','a','b'],[true]));});
test('preview lookup requires published lesson and course and excludes private fields',async()=>{let query;const Page=load('app/courses/[slug]/preview/[lessonId]/page.tsx',{'@/lib/prisma':{prisma:{lesson:{findFirst:async(q)=>{query=q;return null;}}}},'next/navigation':{notFound:()=>{throw Error('404')}},'next/link':{default:()=>null}}).default;await assert.rejects(Page({params:Promise.resolve({slug:'course',lessonId:'lesson'})}),/404/);assert.equal(query.where.isPreview,true);assert.equal(query.where.status,'PUBLISHED');assert.equal(query.where.section.course.status,'PUBLISHED');assert.equal(query.select.files,undefined);assert.equal(query.select.assignment,undefined);});
test('legacy password routes no longer bypass SMS verification',async()=>{for(const route of ['login','register'])assert.equal((await load(`app/api/auth/${route}/route.ts`).POST()).status,410);});
test('local OTP shortcut works only in development and is ignored in production',async()=>{const before=process.env.NODE_ENV;process.env.OTP_LOCAL_TEST_CODE='123456';try{process.env.NODE_ENV='development';const dev=setup();const c=await dev.api.requestOtp('09123456789','dev');assert.equal(dev.sent.length,0);assert.ok((await dev.api.verifyOtp(c.challengeId,'123456')).user);process.env.NODE_ENV='production';const prod=setup();await prod.api.requestOtp('09123456789','prod');assert.equal(prod.sent.length,1);}finally{delete process.env.OTP_LOCAL_TEST_CODE;if(before===undefined)delete process.env.NODE_ENV;else process.env.NODE_ENV=before;}});
