import Link from 'next/link';
import {redirect} from 'next/navigation';
import {communicationActor,pageNumber} from '@/lib/communication';
import {prisma} from '@/lib/prisma';
import {AnnouncementForm} from '@/components/communication/forms';
const audienceLabels:Record<string,string>={ALL:'همهٔ کاربران',STUDENT:'دانش‌آموزان',TEACHER:'مدرس‌ها',COURSE:'ثبت‌نام‌شدگان دوره',USER:'کاربر مشخص'};
export default async function AdminNotifications({searchParams}:{searchParams:Promise<{page?:string}>}){
 const actor=await communicationActor();if(!actor)redirect('/login');if(actor.role!=='ADMIN')redirect('/dashboard');
 const count=await prisma.notificationDispatch.count();const pages=Math.max(1,Math.ceil(count/20));const page=Math.min(pageNumber((await searchParams).page),pages);
 const rows=await prisma.notificationDispatch.findMany({orderBy:[{createdAt:'desc'},{id:'desc'}],skip:(page-1)*20,take:20,include:{sender:{select:{name:true}}}});
 return <main className="mx-auto max-w-6xl px-4 py-8"><h1 className="mb-3 text-2xl font-bold">ارسال اعلان</h1><p className="mb-6 text-sm leading-7 text-slate-500">اعلان عمومی یا اختصاصی ارسال کنید. اعلان‌های خودکار درس، تکلیف، ارزیابی و تیکت جداگانه در حساب گیرنده ثبت می‌شوند.</p><div className="grid items-start gap-6 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-6"><h2 className="mb-5 text-lg font-bold">اعلان جدید</h2><AnnouncementForm/></section><section className="rounded-2xl border bg-white p-6"><h2 className="mb-5 text-lg font-bold">تاریخچهٔ ارسال مدیران</h2><div className="space-y-4">{rows.map(row=><article key={row.id} className="border-b border-slate-100 pb-4"><h3 className="break-words font-semibold">{row.title}</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-slate-600">{row.body}</p><p className="mt-3 text-xs leading-7 text-slate-500">{audienceLabels[row.audience]} · {row.recipientCount.toLocaleString('fa-IR')} گیرنده · {row.sender.name||'مدیر'} · {row.createdAt.toLocaleString('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'})}</p></article>)}</div>{!rows.length&&<p className="text-sm text-slate-500">هنوز اعلانی توسط مدیر ارسال نشده است.</p>}<nav className="mt-5 flex items-center justify-center gap-3">{page>1&&<Link scroll={false} href={`?page=${page-1}`} className="panel-action panel-action-slate">قبل</Link>}<span className="text-sm">{page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span>{page<pages&&<Link scroll={false} href={`?page=${page+1}`} className="panel-action panel-action-slate">بعد</Link>}</nav></section></div></main>;
}
