
import ThemeIcon from '@/components/panel/theme-icon';
import Link from 'next/link';
import {redirect} from 'next/navigation';
import {communicationActor,pageNumber,ticketScope,userLabel} from '@/lib/communication';
import {prisma} from '@/lib/prisma';
import {NewTicketForm} from '@/components/communication/forms';
export default async function Tickets({searchParams}:{searchParams:Promise<{status?:string;page?:string}>}){
 const actor=await communicationActor();if(!actor)redirect('/login');
 const query=await searchParams;const status=['OPEN','CLOSED'].includes(query.status||'')?query.status:undefined;
 const where={...ticketScope(actor),...(status?{status}:{})};
 const count=await prisma.ticket.count({where});const pages=Math.max(1,Math.ceil(count/20));const page=Math.min(pageNumber(query.page),pages);
 const rows=await prisma.ticket.findMany({where,orderBy:[{updatedAt:'desc'},{id:'desc'}],skip:(page-1)*20,take:20,include:{creator:{select:{id:true,name:true,role:true}},recipient:{select:{id:true,name:true,role:true}},_count:{select:{messages:true}}}});
 return <main className="mx-auto max-w-7xl px-4 py-8"><header className="mb-7"><h1 className="text-2xl font-bold">{actor.role==='ADMIN'?'مدیریت تیکت‌ها':'تیکت‌ها و گفت‌وگوها'}</h1><p className="mt-2 text-sm leading-7 text-slate-500">{actor.role==='ADMIN'?'همهٔ گفت‌وگوها و درخواست‌های پشتیبانی در این بخش قابل پیگیری است.':'پیام‌های شما با مدیریت و مخاطبان مشخص، به همراه تاریخچهٔ پاسخ‌ها.'}</p></header><div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><section><nav className="mb-5 flex gap-2" aria-label="فیلتر تیکت‌ها">{[['','همه'],['OPEN','باز'],['CLOSED','بسته']].map(([value,label])=><Link key={value} scroll={false} href={`?status=${value}`} aria-current={(status||'')===value?'page':undefined} className={`panel-action ${(status||'')===value?'panel-action-primary':'panel-action-slate'}`}>{label}</Link>)}</nav><p className="mb-3 text-sm text-slate-500">{count.toLocaleString('fa-IR')} گفت‌وگو</p><div className="space-y-3">{rows.map(ticket=><article key={ticket.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><h2 className="break-words font-semibold">{ticket.subject}</h2><span className={`shrink-0 rounded-full px-3 py-1 text-xs ${ticket.status==='OPEN'?'bg-teal-50 text-teal-800':'bg-slate-100 text-slate-600'}`}>{ticket.status==='OPEN'?'باز':'بسته'}</span></div><p className="mt-3 text-sm text-slate-500">{userLabel(ticket.creator)} · {ticket.recipient?userLabel(ticket.recipient):'پشتیبانی مدیریت'}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-500">{ticket.updatedAt.toLocaleString('fa-IR',{timeZone:'Asia/Tehran',dateStyle:'medium',timeStyle:'short'})} · {ticket._count.messages.toLocaleString('fa-IR')} پیام</span><Link href={`/tickets/${ticket.id}`} className="panel-action"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>مشاهدهٔ گفت‌وگو</Link></div></article>)}</div>{!rows.length&&<p className="rounded-2xl border bg-white p-8 text-sm text-slate-500">تیکتی در این فهرست وجود ندارد.</p>}<nav className="mt-5 flex items-center justify-center gap-3">{page>1&&<Link scroll={false} href={`?status=${status||''}&page=${page-1}`} className="panel-action panel-action-slate"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>قبل</Link>}<span className="text-sm">{page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span>{page<pages&&<Link scroll={false} href={`?status=${status||''}&page=${page+1}`} className="panel-action panel-action-slate"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>بعد</Link>}</nav></section><aside className="rounded-2xl border border-slate-200 bg-white p-6"><NewTicketForm role={actor.role}/></aside></div></main>;
}
