import type { Payout } from "@prisma/client";
import LedgerForm from "@/components/finance/ledger-form";
export const financeDate=(value:Date)=>new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tehran'}).format(value);
export default function PayoutCard({payout,admin=false,name,actorId}:{payout:Payout & {reviews?:{id:string;action:string;message:string;createdAt:Date}[]};admin?:boolean;name?:string;actorId?:string}) {
 return <article className="rounded-2xl border border-slate-200 bg-white p-5">
  <div className="flex flex-wrap justify-between gap-3"><h3 className="font-bold">{name??'درخواست برداشت'} · {payout.amount.toLocaleString('fa-IR')} تومان</h3><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{payout.status==='REQUESTED'?'در انتظار واریز':payout.status==='PROCESSING'?'در حال واریز':payout.status==='REJECTED'?'ردشده':payout.receivedAt?'دریافت تأیید شده':'واریزشده؛ منتظر تأیید دریافت'}</span></div>
  <p className="mt-3 text-xs leading-7 text-slate-500">درخواست: {financeDate(payout.requestedAt)} · مبنای محاسبهٔ درآمد: {financeDate(payout.cutoffAt)}</p>
  <p className="mt-2 break-all text-sm"><bdi>{payout.accountName}</bdi> · <bdi>{payout.iban}</bdi></p>
  {payout.paidAt&&<p className="mt-3 text-sm leading-8">واریز ثبت‌شده{payout.status==='REJECTED'?' (برگشت‌خورده)':''}: {financeDate(payout.paidAt)} · کارمزد: {payout.fee.toLocaleString('fa-IR')} · خالص دریافتی: {(payout.amount-payout.fee).toLocaleString('fa-IR')} تومان · پیگیری: <bdi>{payout.reference}</bdi></p>}
  {payout.receivedAt&&<p className="text-xs text-emerald-700">تأیید دریافت مدرس: {financeDate(payout.receivedAt)}</p>}
  {payout.note&&<p className="mt-3 text-sm text-amber-800">{payout.note}</p>}
  {!admin&&payout.status==='PAID'&&!payout.receivedAt&&<LedgerForm action="receive" fixed={{id:payout.id}} label="وجه را دریافت کردم" />}
  {!admin&&payout.status==='PAID'&&!payout.receivedAt&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-rose-700">وجه را دریافت نکرده‌ام</summary><p className="mt-2 text-xs leading-7">گزارش برای مدیر ثبت می‌شود؛ تا بررسی بانکی، مبلغ آزاد یا دوباره واریز نمی‌شود.</p><LedgerForm action="dispute" fixed={{id:payout.id}} fields={[{name:'reason',label:'توضیح عدم دریافت'}]} label="ثبت گزارش عدم دریافت"/></details>}
  {payout.disputedAt&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><p>گزارش عدم دریافت: {payout.disputeReason}</p><p className="mt-2">{payout.receivedAt?'دریافت بعداً تأیید شد':payout.reviewedAt?'پاسخ مدیر: '+payout.reviewNote:'در انتظار بررسی مدیر'}</p></div>}
  {admin&&payout.status==='PAID'&&payout.disputedAt&&!payout.receivedAt&&<div className="mt-4 border-t pt-4"><LedgerForm action="review" fixed={{id:payout.id}} fields={[{name:'reason',label:'نتیجهٔ بررسی و پیگیری بانکی'}]} label="ثبت پاسخ به مدرس"/><details className="mt-4 text-sm"><summary className="cursor-pointer text-rose-700">اصلاح واریز انجام‌نشده و بازگرداندن مانده</summary><p className="mt-2 text-xs leading-7">فقط پس از احراز اینکه وجه به مدرس نرسیده و انتقال بانکی ناموفق یا برگشت‌خورده است. سابقه و شماره پیگیری حفظ می‌شود؛ مدرس می‌تواند درخواست جدید بدهد. برای انتقال در حال پیگیری این گزینه را نزنید.</p><LedgerForm action="reverse" fixed={{id:payout.id}} fields={[{name:'reason',label:'مدرک و علت برگشت انتقال'}]} label="تأیید انجام‌نشدن واریز و اصلاح مانده" confirmText="آیا ناموفق بودن یا برگشت انتقال بانکی را احراز کرده‌اید؟ اثر این تسویه از مانده برداشته می‌شود."/></details></div>}
  {!!payout.reviews?.length&&<details className="mt-4 text-xs"><summary className="cursor-pointer text-indigo-700">تاریخچهٔ پیگیری</summary>{payout.reviews.map(review=><p key={review.id} className="mt-2 border-t py-2">{financeDate(review.createdAt)} · {review.action==='dispute'?'گزارش مدرس':review.action==='reverse'?'برگشت ثبت واریز':'پاسخ مدیر'}: {review.message}</p>)}</details>}
  {admin&&payout.status==='REQUESTED'&&<LedgerForm action="begin" fixed={{id:payout.id}} label="رزرو درخواست برای واریز" />}
  {admin&&payout.status==='PROCESSING'&&payout.processedBy!==actorId&&<p className="mt-4 text-sm text-amber-800">مدیر دیگری مسئول این واریز است؛ دوباره وجه واریز نکنید.</p>}
  {admin&&['REQUESTED','PROCESSING'].includes(payout.status)&&(payout.status==='REQUESTED'||payout.processedBy===actorId)&&<>
    <p className="mt-4 text-xs leading-7 text-slate-500">پس از واریز واقعی ثبت کنید. کارمزد انتقال از مبلغ درخواست کم می‌شود؛ خالص واریز = مبلغ درخواست − کارمزد.</p>
    {payout.status==='PROCESSING'&&<LedgerForm action="pay" fixed={{id:payout.id}} label="ثبت واریز انجام‌شده" fields={[{name:'fee',label:'کارمزد انتقال (تومان)',type:'number',value:0,min:0,max:payout.amount-1},{name:'reference',label:'شماره پیگیری بانکی'},{name:'paidAt',label:'تاریخ و ساعت واریز',type:'datetime-local'}]} />}
    <details className="mt-4 text-sm"><summary className="cursor-pointer text-rose-700">رد درخواست و آزادسازی مبلغ</summary><LedgerForm action="reject" fixed={{id:payout.id}} fields={[{name:'reason',label:'دلیل رد'}]} label="رد درخواست" /></details>
  </>}
 </article>;
}
