'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {Prerequisite} from '@/lib/course-prerequisites';
import ThemeIcon from '@/components/panel/theme-icon';
export default function PrerequisitesForm({courseId,initial,options}:{courseId:string;initial:Prerequisite[];options:{id:string;title:string}[]}){
 const [items,setItems]=useState(initial),[text,setText]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const router=useRouter();
 function add(item:Prerequisite){if(items.length<20&&!items.some(x=>item.courseId?x.courseId===item.courseId:x.title===item.title))setItems([...items,item]);}
 return <section className="assessment-card my-6"><h2 className="assessment-heading"><ThemeIcon name="layers"/>پیش‌نیازهای دوره</h2><p className="my-3 text-sm leading-7 text-slate-500">این موارد راهنمای آمادگی دانش‌آموز هستند و خرید را محدود نمی‌کنند. حداکثر بیست مورد.</p><fieldset disabled={busy} className="assessment-form space-y-4"><label>انتخاب دورهٔ موجود<select value="" onChange={e=>{const c=options.find(c=>c.id===e.target.value);if(c)add({courseId:c.id,title:c.title});}}><option value="">انتخاب دوره</option>{options.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>یا نام پیش‌نیاز خارج از دوره‌ها<input value={text} maxLength={200} onChange={e=>setText(e.target.value)}/></label><button className="panel-action" onClick={()=>{if(text.trim().length>=2){add({title:text.trim()});setText('');}}} type="button">افزودن پیش‌نیاز</button><ul className="space-y-2">{items.map((item,i)=><li className="flex items-center justify-between gap-3 rounded-xl bg-indigo-50 p-3" key={i}><span>{item.title}</span><button className="panel-action" type="button" aria-label={`حذف ${item.title}`} onClick={()=>setItems(items.filter((_,n)=>n!==i))}><ThemeIcon name="trash"/></button></li>)}</ul><button className="panel-action panel-action-primary" type="button" onClick={async()=>{setBusy(true);setMessage('');try{const res=await fetch(`/api/courses/${courseId}/prerequisites`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(items)});const data=await res.json();if(!res.ok)throw Error(data.message);setMessage('پیش‌نیازها ذخیره شدند.');router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'ذخیره نشد.');}finally{setBusy(false);}}}>{busy?'در حال ذخیره…':'ذخیرهٔ پیش‌نیازها'}</button></fieldset><p role="status" className="mt-3 text-sm">{message}</p></section>;
}
