"use client";

import ThemeIcon from '@/components/panel/theme-icon';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import NumberInput from '@/components/ui/number-input';
const field='mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm';
function useSave(){const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const router=useRouter();return {busy,message,save:async(url:string,method:string,body:unknown)=>{setBusy(true);setMessage('');try{const res=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await res.json();setMessage(json.message);if(res.ok)router.refresh();}catch{setMessage('ارتباط برقرار نشد؛ دوباره تلاش کنید.');}finally{setBusy(false);}}};}
function Result({busy,message,label}:{busy:boolean;message:string;label:string}){return <><button disabled={busy} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm text-white disabled:opacity-40"><ThemeIcon name="check" className="me-2 h-4 w-4"/>{busy?'در حال ثبت…':label}</button>{message&&<p role="status" className="text-sm leading-7">{message}</p>}</>;}
export function AssignmentEditor({lessonId,assignment}:{lessonId:string;assignment:{title:string;instructions:string;published:boolean;version:number}|null}){
 const state=useSave();
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);await state.save(`/api/assignments/${lessonId}`,'PUT',{title:form.get('title'),instructions:form.get('instructions'),published:form.get('published')==='on',version:assignment?.version??0});}
 return <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">تکلیف درس</h2><p className="my-3 text-sm leading-8 text-slate-600">برای هر درس یک تکلیف متنی یا لینک پروژه تعریف کنید. نمایش آن نیازمند انتشار درس و دوره است. ارزیابی تکلیف در این مرحله شرط باز شدن درس بعدی نیست. پاسخ‌های قبلی همراه با صورت تکلیف زمان ارسال حفظ می‌شوند.</p><form key={assignment?.version??0} onSubmit={submit} className="space-y-4"><label className="block text-sm">عنوان تکلیف<input required name="title" minLength={3} maxLength={150} defaultValue={assignment?.title} className={field}/></label><label className="block text-sm">صورت تکلیف و معیار ارزیابی<textarea required name="instructions" minLength={10} maxLength={10000} rows={6} defaultValue={assignment?.instructions} className={field}/></label><label className="flex items-center gap-2 text-sm"><input name="published" type="checkbox" defaultChecked={assignment?.published??false}/>نمایش تکلیف و پذیرش پاسخ</label><Result {...state} label="ذخیرهٔ تکلیف"/></form></section>;
}
export function SubmissionForm({lessonId,version,previous}:{lessonId:string;version:number;previous?:{answer:string;projectUrl:string|null}}){
 const state=useSave();return <form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);await state.save(`/api/assignments/${lessonId}/submit`,'POST',{answer:form.get('answer'),projectUrl:form.get('projectUrl'),version});}}><label className="block text-sm">پاسخ و توضیح کار شما<textarea name="answer" required minLength={3} maxLength={12000} rows={6} defaultValue={previous?.answer} className={field}/></label><label className="block text-sm">لینک پروژه (اختیاری؛ HTTPS)<input name="projectUrl" type="url" maxLength={2000} defaultValue={previous?.projectUrl??''} placeholder="https://…" dir="ltr" className={field}/></label><p className="text-xs leading-7 text-slate-500">پاسخ برای مدرس و مدیر قابل مشاهده است. پس از ارسال، ویرایش فقط با درخواست اصلاح مدرس ممکن است؛ نسخهٔ قبلی حفظ می‌شود.</p><Result {...state} label={previous?'ارسال پاسخ اصلاح‌شده':'ارسال پاسخ برای مدرس'}/></form>;
}
export function ReviewForm({submissionId}:{submissionId:string}){
 const [action,setAction]=useState('grade');const state=useSave();return <form className="mt-5 space-y-4 border-t pt-5" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);await state.save(`/api/submissions/${submissionId}/review`,'POST',{action,feedback:form.get('feedback'),...(action==='grade'?{score:Number(form.get('score'))}:{})});}}><label className="block text-sm">نتیجهٔ بررسی<select value={action} onChange={e=>setAction(e.target.value)} className={field}><option value="grade">ثبت نمرهٔ نهایی</option><option value="revision">نیاز به اصلاح و ارسال مجدد</option></select></label>{action==='grade'&&<label className="block text-sm">نمره از صد<NumberInput name="score" required min={0} max={100} unit="از صد" className={field}/></label>}<label className="block text-sm">بازخورد مدرس<textarea required name="feedback" minLength={3} maxLength={4000} rows={3} className={field}/></label><p className="text-xs leading-7 text-slate-500">نمرهٔ نهایی این پاسخ پس از ثبت قابل بازنویسی نیست؛ برای فرصت ارسال دوباره، «نیاز به اصلاح» را انتخاب کنید.</p><Result {...state} label="ثبت ارزیابی"/></form>;
}
