ALTER TABLE "Course" ADD COLUMN "discountPercent" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "demoBatchId" TEXT;
ALTER TABLE "Course" ADD CONSTRAINT "Course_discountPercent_check" CHECK ("discountPercent" BETWEEN 0 AND 100);
ALTER TABLE "User" ADD COLUMN "demoBatchId" TEXT;
CREATE TABLE "DemoBatch" ("id" TEXT PRIMARY KEY, "ownerId" TEXT NOT NULL UNIQUE, "teacherId" TEXT NOT NULL UNIQUE, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
