import Link from 'next/link';
import {redirect} from 'next/navigation';
import {getManagementSession} from '@/lib/management-session';
import {prisma} from '@/lib/prisma';
import {CertificateButton,RevokeCertificate} from '@/components/assessment/certificate-actions';
export default async function Certificates({searchParams}:{searchParams:Promise<{page?:string;courseId?:string;studentPage?:string}>}){
 if((await getManagementSession())?.role!=='ADMIN')redirect('/login');
 const query=await searchParams;const page=Math.floor(Math.max(1,Math.min(10000,Number(query.page)||1)));
 const courses=await prisma.course.findMany({where:{demoBatchId:null},select:{id:true,title:true},orderBy:{title:'asc'}});
 const courseId=courses.some(c=>c.id===query.courseId)?query.courseId:undefined;
 const studentPage=Math.floor(Math.max(1,Math.min(10000,Number(query.studentPage)||1)));
 const students=courseId?await prisma.enrollment.findMany({where:{courseId,status:{not:'CANCELLED'},user:{role:'STUDENT',demoBatchId:null}},include:{user:{select:{name:true}},certificate:{select:{id:true}}},orderBy:{id:'asc'},skip:(studentPage-1)*20,take:21}):[];
 const rows=await prisma.certificate.findMany({orderBy:{issuedAt:'desc'},skip:(page-1)*30,take:31,include:{enrollment:{select:{status:true}}}});
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><h1 className="text-2xl font-bold">مرکز گواهی‌نامه‌ها</h1><Link className="panel-action panel-action-primary" href="/admin/certificates/templates">طراحی، پیش‌نمایش و انتخاب قالب دوره</Link><section className="assessment-card space-y-5"><h2 className="assessment-heading">صدور برای دانش‌آموز</h2><p className="text-sm leading-8">ابتدا دوره را انتخاب کنید. صدور فقط پس از تکمیل درس‌ها، تصحیح تمرین‌ها و قبولی در آزمون و کارنامه امکان‌پذیر است.</p><form className="flex flex-wrap gap-3"><select name="courseId" defaultValue={courseId||''} className="min-w-0 max-w-full rounded-xl border p-3" aria-label="انتخاب دوره"><option value="">انتخاب دوره</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><button className="panel-action" type="submit">نمایش دانش‌آموزان</button></form>{students.slice(0,20).map(e=><article key={e.id} className="rounded-xl border p-4"><h3 className="font-bold">{e.user.name||'دانش‌آموز'}</h3><Link className="panel-action mt-3" href={`/teacher/courses/${e.courseId}/students/${e.id}`}>بررسی کارنامه</Link>{e.certificate?<Link className="panel-action m-3" href={`/certificates/${e.certificate.id}`}>مشاهدهٔ مدرک صادرشده</Link>:<CertificateButton enrollmentId={e.id}/>}</article>)}{courseId&&!students.length&&<p>دانش‌آموزی یافت نشد.</p>}<nav className="flex gap-3">{studentPage>1&&<Link className="panel-action" href={`?courseId=${courseId}&studentPage=${studentPage-1}`}>دانش‌آموزان قبلی</Link>}{students.length>20&&<Link className="panel-action" href={`?courseId=${courseId}&studentPage=${studentPage+1}`}>دانش‌آموزان بعدی</Link>}</nav></section><h2 className="text-xl font-bold">گواهی‌نامه‌های صادرشده</h2><p className="text-sm leading-8">صدور از کارنامهٔ نهایی دانش‌آموز انجام می‌شود. گواهی تصویر ثابت نمره و نام در زمان صدور است. ابطال توسط مدیر یا لغو ثبت‌نام، استعلام را نامعتبر می‌کند.</p><section className="assessment-card space-y-4">{rows.slice(0,30).map(c=><article key={c.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4"><div><h2 className="font-bold">{c.studentName} · {c.courseTitle}{c.isTest?' · آزمایشی':''}</h2><p className="mt-2 text-sm">نمره: {c.score.toLocaleString('fa-IR')} · {c.revokedAt||c.enrollment.status==='CANCELLED'?'نامعتبر':'معتبر'}</p></div><div className="flex flex-wrap gap-3"><Link className="panel-action" href={`/certificates/${c.id}`}>مشاهده و استعلام</Link>{!c.revokedAt&&<RevokeCertificate id={c.id}/>}</div></article>)}{!rows.length&&<p>هنوز گواهی صادر نشده است.</p>}</section><nav className="flex gap-3">{page>1&&<Link className="panel-action" href={`?page=${page-1}`}>قبل</Link>}{rows.length>30&&<Link className="panel-action" href={`?page=${page+1}`}>بعد</Link>}</nav></main>;
}
