import Link from 'next/link';
import {redirect} from 'next/navigation';
import {getManagementSession} from '@/lib/management-session';
import {prisma} from '@/lib/prisma';
import {SmsForm,SmsRunner} from '@/components/communication/admin-tools';
import StartSmsControl from '@/components/course/start-sms-control';
export default async function SmsPage({searchParams}:{searchParams:Promise<{page?:string;campaign?:string;after?:string}>}){
 if((await getManagementSession())?.role!=='ADMIN')redirect('/login');
 const query=await searchParams;const page=Math.max(1,Math.min(10000,Number(query.page)||1));
 const [courses,campaigns,details]=await Promise.all([
 prisma.course.findMany({where:{demoBatchId:null,status:'PUBLISHED',deliveryStatus:'ONGOING',interests:{some:{}}},select:{id:true,title:true,_count:{select:{interests:true}}},orderBy:{updatedAt:'desc'}}),
 prisma.smsCampaign.findMany({orderBy:{createdAt:'desc'},skip:(Math.floor(page)-1)*20,take:21,include:{_count:{select:{deliveries:true}}}}),
 query.campaign?prisma.smsDelivery.findMany({where:{campaignId:query.campaign,...(query.after?{id:{gt:query.after}}:{})},orderBy:{id:'asc'},take:51}):Promise.resolve([])]);
 const stats=query.campaign?await prisma.smsDelivery.groupBy({by:['status'],where:{campaignId:query.campaign},_count:true}):[];
 const labels:Record<string,string>={PENDING:'در صف',SENDING:'در حال ارسال',SENT:'پذیرفته‌شده توسط سرویس',FAILED:'ردشده',UNKNOWN:'نتیجه نامشخص'};
 return <main className="mx-auto max-w-6xl space-y-7 p-6"><header><h1 className="text-2xl font-bold">مرکز پیامک مدیر</h1><p className="mt-3 text-sm leading-8">ارسال فقط با دکمهٔ مدیر انجام می‌شود. هنگام ارسال صفحه باز بماند؛ توقف یا بستن صفحه، ادامهٔ صف را به اجرای بعدی موکول می‌کند. پذیرش سرویس به معنی رسیدن به گوشی نیست.</p><Link className="panel-action mt-3" href="/admin/coupons">مدیریت کدهای تخفیف</Link></header><section className="assessment-card"><h2 className="assessment-heading mb-5">اعلام آغاز دوره</h2><div className="space-y-4">{courses.map(c=><details className="course-chapter" key={c.id}><summary className="p-4 font-bold">{c.title} · {c._count.interests.toLocaleString('fa-IR')} متقاضی</summary><div className="p-5"><StartSmsControl courseId={c.id}/><Link className="panel-action" href={`/teacher/courses/${c.id}/interests`}>فهرست متقاضیان و گزارش ارسال</Link></div></details>)}{!courses.length&&<p>دورهٔ آغازشده با متقاضی پیش‌ثبت‌نام وجود ندارد.</p>}</div></section><div className="grid items-start gap-6 lg:grid-cols-2"><section className="assessment-card"><h2 className="assessment-heading mb-5">پیامک گروهی جدید</h2><SmsForm/></section><section className="assessment-card space-y-4"><h2 className="assessment-heading">تاریخچهٔ ارسال گروهی</h2>{campaigns.slice(0,20).map(c=><article key={c.id} className="rounded-xl border p-4"><p className="text-sm leading-7">{{ALL:'همهٔ کاربران',TEACHER:'مدرس‌ها',STUDENT:'دانش‌آموزان'}[c.audience]} · {c._count.deliveries.toLocaleString('fa-IR')} شماره · {c.createdAt.toLocaleString('fa-IR',{timeZone:'Asia/Tehran'})}</p><p className="my-2 break-words text-sm">{c.patternCode?`پترن: ${c.patternCode}`:c.message}</p><SmsRunner campaignId={c.id}/><Link scroll={false} href={`?page=${page}&campaign=${c.id}`} className="panel-action">گزارش شماره‌ها</Link></article>)}<nav className="flex gap-3">{page>1&&<Link scroll={false} href={`?page=${page-1}`} className="panel-action">قبل</Link>}{campaigns.length>20&&<Link scroll={false} href={`?page=${page+1}`} className="panel-action">بعد</Link>}</nav></section></div>{query.campaign&&<section className="assessment-card"><h2 className="assessment-heading">گزارش ارسال</h2><p className="my-4 text-sm leading-8">{stats.map(s=>`${labels[s.status]}: ${s._count.toLocaleString('fa-IR')}`).join(' · ')}</p><p className="text-xs leading-7">نتیجهٔ نامشخص را ابتدا در پنل سرویس پیامک بررسی کنید. این موارد خودکار تکرار نمی‌شوند.</p>{details.slice(0,50).map(d=><div className="flex flex-wrap items-center justify-between gap-3 border-b py-3" key={d.id}><bdi>{d.phone}</bdi><span>{labels[d.status]}</span>{['FAILED','UNKNOWN'].includes(d.status)&&<SmsRunner campaignId={d.campaignId} retryId={d.id}/>}</div>)}{details.length>50&&<Link scroll={false} className="panel-action mt-4" href={`?page=${page}&campaign=${query.campaign}&after=${details[49].id}`}>شماره‌های بعدی</Link>}</section>}</main>;
}
