
import ThemeIcon from '@/components/panel/theme-icon';
import Link from 'next/link';
import {prisma} from '@/lib/prisma';
import {teachingCourse} from '@/lib/assignment-pages';
import SubmissionCard from '@/components/assignments/submission-card';
import {ReviewForm} from '@/components/assignments/forms';
export default async function CourseAssignments({params,searchParams}:{params:Promise<{courseId:string}>;searchParams:Promise<{status?:string;page?:string}>}) {
 const {courseId}=await params;const course=await teachingCourse(courseId);const query=await searchParams;
 const status=['GRADED','REVISION','ALL'].includes(query.status??'')?query.status!:'PENDING';
 const where={assignment:{lesson:{section:{courseId}}},...(status==='ALL'?{}:{status,isLatest:true})};
 const count=await prisma.submission.count({where});const pages=Math.max(1,Math.ceil(count/20));const raw=Number(query.page);const page=Number.isSafeInteger(raw)&&raw>0?Math.min(raw,pages):1;
 const submissions=await prisma.submission.findMany({where,orderBy:[{createdAt:'desc'},{id:'asc'}],take:20,skip:(page-1)*20,include:{enrollment:{select:{user:{select:{name:true,email:true}},status:true}},assignment:{select:{lesson:{select:{title:true,id:true,sectionId:true}}}}}});
 const assignments=await prisma.assignment.findMany({where:{lesson:{section:{courseId}}},select:{id:true,title:true,published:true,lesson:{select:{id:true,sectionId:true}},_count:{select:{submissions:true}}}});
 return <main className="mx-auto max-w-6xl px-4 py-8"><Link href={`/teacher/courses/${courseId}`} className="panel-action panel-action-indigo"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>بازگشت به دوره</Link><h1 className="my-5 text-2xl font-bold">تکلیف‌ها و ارزیابی · {course.title}</h1><p className="text-sm leading-8 text-slate-600">برای تعریف تکلیف وارد صفحهٔ مدیریت هر درس شوید. فیلترها آخرین ارسال هر دانش‌آموز را نشان می‌دهند و «همهٔ ارسال‌ها» شامل تاریخچه است. هر ارسال جدا نگه‌داری می‌شود؛ درخواست اصلاح نمرهٔ نهایی نیست و امکان ارسال نسخهٔ جدید می‌دهد.</p><div className="my-6 grid gap-3 sm:grid-cols-2">{assignments.map(a=><Link key={a.id} href={`/teacher/courses/${courseId}/sections/${a.lesson.sectionId}/lessons/${a.lesson.id}`} className="rounded-xl border bg-white p-4 text-sm"><ThemeIcon name="message" className="me-2 h-4 w-4"/>{a.title} · {a.published?'پذیرش پاسخ فعال':'غیرفعال'} · {a._count.submissions.toLocaleString('fa-IR')} ارسال</Link>)}</div>{!assignments.length&&<p className="my-5 rounded-xl border bg-white p-5">هنوز تکلیفی تعریف نشده است. از مدیریت درس، بخش «تکلیف درس» شروع کنید.</p>}<nav aria-label="وضعیت پاسخ تکلیف" className="my-5 flex flex-wrap gap-2">{[['PENDING','منتظر بررسی'],['REVISION','نیاز به اصلاح'],['GRADED','نمره‌دار'],['ALL','همهٔ ارسال‌ها']].map(([key,label])=><Link scroll={false} key={key} href={`?status=${key}`} aria-current={status===key?'page':undefined} className={`rounded-xl px-4 py-2 text-sm ${status===key?'bg-indigo-600 text-white':'border bg-white'}`}>{label}</Link>)}</nav><p className="mb-4 text-sm">{count.toLocaleString('fa-IR')} ارسال در این فیلتر</p><div className="space-y-6">{submissions.map(s=><article key={s.id} className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">{s.enrollment.user.name||s.enrollment.user.email||'دانش‌آموز'} · {s.assignment.lesson.title}</h2>{s.enrollment.status==='CANCELLED'&&<p className="mb-3 text-sm text-amber-800">ثبت‌نام این دانش‌آموز لغو شده؛ این پاسخ سابقهٔ قبلی است.</p>}<SubmissionCard submission={s}/>{s.status==='PENDING'&&<ReviewForm submissionId={s.id}/>}</article>)}</div>{!submissions.length&&<p className="rounded-xl border bg-white p-5">پاسخی با این وضعیت وجود ندارد.</p>}<nav className="my-6 flex justify-center gap-4 text-sm">{page>1&&<Link scroll={false} href={`?status=${status}&page=${page-1}`} className="panel-action panel-action-slate"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>قبل</Link>}<span>{page.toLocaleString('fa-IR')} از {pages.toLocaleString('fa-IR')}</span>{page<pages&&<Link scroll={false} href={`?status=${status}&page=${page+1}`} className="panel-action panel-action-slate"><ThemeIcon name="arrow" className="me-2 h-4 w-4"/>بعد</Link>}</nav></main>;
}
