import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {devTestingEnabled} from '@/lib/dev-test-policy';
import {devTestOwner} from '@/lib/dev-test-accounts';
import {getManagementSession} from '@/lib/management-session';
import {prisma} from '@/lib/prisma';
import {TestAccountAction} from '@/components/panel/dev-test-controls';
export default async function Testing(){
 if(!devTestingEnabled())notFound();if((await getManagementSession())?.role!=='ADMIN')redirect('/login');
 const owner=await devTestOwner();if(!owner)redirect('/login');const users=await prisma.user.findMany({where:{testOwnerId:owner.id},include:{courses:{select:{id:true,title:true,slug:true}},enrollments:{include:{course:{select:{title:true,slug:true}}}}},orderBy:[{role:'asc'},{createdAt:'asc'}]});
 return <main className="mx-auto max-w-6xl space-y-6 p-6"><header><h1 className="text-2xl font-bold">آزمایش نقش‌ها و حساب‌ها</h1><p className="mt-3 text-sm leading-8">با همان ورود پیامکی مدیر، بین حساب‌های مستقل آزمایشی جابه‌جا شوید. حساب و نقش اصلی شما تغییر نمی‌کند. هر تغییر داخل این حساب‌ها واقعاً در دیتابیس توسعه ثبت می‌شود.</p></header><section className="assessment-card"><h2 className="assessment-heading mb-4">سناریوی آمادهٔ تست</h2><p className="mb-4 text-sm leading-8">دو مدرس، دو دانش‌آموز و دو دورهٔ رایگان با درس، تمرین و آزمون ساخته می‌شود. هر دانش‌آموز در دورهٔ یکی از مدرس‌ها ثبت‌نام دارد. دکمهٔ ساخت، دادهٔ موجود را دوباره ایجاد یا پاک نمی‌کند.</p><TestAccountAction action="create" label={users.length?'بررسی حساب‌های ساخته‌شده':'ساخت حساب‌ها و دوره‌های آزمایشی'}/></section><div className="grid gap-5 md:grid-cols-2">{users.map(u=><article className="assessment-card" key={u.id}><h2 className="assessment-heading">{u.name}</h2><p className="my-3 text-sm">{u.role==='TEACHER'?'مدرس':'دانش‌آموز'} · بدون نیاز به شمارهٔ جدید</p><div className="mb-4 space-y-2">{u.courses.map(c=><Link className="panel-action" href={`/teacher/courses/${c.id}`} key={c.id}>{c.title}</Link>)}{u.enrollments.map(e=><p className="text-xs leading-7" key={e.id}>{e.course.title}</p>)}</div><TestAccountAction action="switch" userId={u.id} label="ورود به این حساب"/></article>)}</div><section className="assessment-card"><h2 className="assessment-heading mb-4">مسیر پیشنهادی تست مدرک</h2><ol className="list-inside list-decimal space-y-3 text-sm leading-8"><li>با دانش‌آموز اول، درس را تکمیل کنید، تمرین بفرستید و آزمون بدهید.</li><li>به مدیر برگردید و با مدرس اول وارد شوید؛ تمرین را نمره بدهید.</li><li>در نقش مدرس دوم، بررسی کنید دوره و دانش‌آموز مدرس اول قابل مدیریت نباشد.</li><li>در نقش مدیر برای دوره قالب انتخاب کنید؛ سپس مدرک را از مرکز مدارک یا کارنامهٔ دانش‌آموز صادر کنید.</li></ol><p className="mt-4 text-xs leading-7">مدرک این حساب‌ها نشان «آزمایشی» دارد. پرداخت واقعی با آن‌ها بسته است؛ برای تست درگاه باید حالت Sandbox فعال باشد. خروج عادی، حالت آزمایش و امکان بازگشت سریع را می‌بندد.</p></section></main>;
}
